/* Converted from import_pointers.S */
#include "common_types.h"

extern void Com_Error(void);
extern void FS_FreeFile(void);
extern void FS_FreeFileList(void);
extern void FS_ListFiles(void);
extern void FS_ReadFile(void);
extern void Hunk_AllocateTempMemoryHighInternal(void);
extern void Hunk_AllocateTempMemoryInternal(void);
extern void Hunk_ClearTempMemory(void);
extern void Hunk_ClearTempMemoryHigh(void);
extern void Hunk_FreeTempMemory(void);
extern void Hunk_OverrideDataForFile(void);
extern void I_strcmp(void);
extern void I_stricmp(void);
extern void Z_FreeInternal(void);
extern void Z_MallocInternal(void);
extern void Z_VirtualCommitInternal(void);
extern void Z_VirtualDecommitInternal(void);
extern void Z_VirtualFreeInternal(void);
extern void Z_VirtualReserveInternal(void);
extern void Com_GetBsp(void);
extern void DObjCreate(void);
extern void Dvar_Reset(void);
extern void R_AddPlume(void);
extern void R_DrawText(void);
extern void R_EndFrame(void);
extern void CM_BoxTrace(void);
extern void CM_SaveLump(void);
extern void Dvar_GetInt(void);
extern void Dvar_SetInt(void);
extern void R_ClearFogs(void);
extern void R_LoadWorld(void);
extern void R_SwitchFog(void);
extern void R_TextWidth(void);
extern void CL_Connect_f(void);
extern void DObjCalcAnim(void);
extern void DObjCalcSkel(void);
extern void DObjGetModel(void);
extern void DObjNumBones(void);
extern void DObjSetModel(void);
extern void Dvar_GetBool(void);
extern void Dvar_SetBool(void);
extern void Dvar_SetVec2(void);
extern void Dvar_SetVec3(void);
extern void Dvar_SetVec4(void);
extern void FS_WriteFile(void);
extern void G_FreeEntity(void);
extern void RB_GpuWaited(void);
extern void R_BeginFrame(void);
extern void R_ClearScene(void);
extern void R_TextHeight(void);
extern void SV_XModelGet(void);
extern void DObjGetBounds(void);
extern void Dvar_GetFloat(void);
extern void Dvar_SetColor(void);
extern void Dvar_SetFloat(void);
extern void FS_FCloseFile(void);
extern void FS_FileExists(void);
extern void FS_FullPath_f(void);
extern void R_ClearFlares(void);
extern void R_Cmd_LoadSun(void);
extern void R_Cmd_SaveSun(void);
extern void R_ImageList_f(void);
extern void R_ModelBounds(void);
extern void R_RenderScene(void);
extern void R_SetCullDist(void);
extern void UI_OpenMenu_f(void);
extern void XModelGetName(void);
extern void Cmd_AddCommand(void);
extern void DObjCreateSkel(void);
extern void DObjGetSurface(void);
extern void Dvar_GetString(void);
extern void Dvar_SetString(void);
extern void RB_UpdateColor(void);
extern void R_PickMaterial(void);
extern void R_RegisterFont(void);
extern void R_SetLodOrigin(void);
extern void UI_CloseMenu_f(void);
extern void XModelGetFlags(void);
extern void XModelGetSkins(void);
extern void XModelNumBones(void);
extern void XModelPrecache(void);
extern void CG_DObjCalcPose(void);
extern void DObjGetBoneInfo(void);
extern void DObjGetSurfaces(void);
extern void R_DuplicateFont(void);
extern void R_EndDebugFrame(void);
extern void R_MarkFragments(void);
extern void R_ParseSunLight(void);
extern void R_RegisterModel(void);
extern void R_ShutdownDebug(void);
extern void StatMon_Warning(void);
extern void CIN_RunCinematic(void);
extern void CL_CubemapShot_f(void);
extern void CM_BoxSightTrace(void);
extern void Cbuf_ExecuteText(void);
extern void DObjGetMatOffset(void);
extern void DObjGetNumModels(void);
extern void Dvar_RegisterInt(void);
extern void Dvar_SetModified(void);
extern void FS_FOpenFileRead(void);
extern void G_RegisterWeapon(void);
extern void R_AddPolyToScene(void);
extern void R_EndCubemapShot(void);
extern void R_GetWorldBounds(void);
extern void SCR_UpdateScreen(void);
extern void XModelGetLodName(void);
extern void XModelGetNumLods(void);
extern void CIN_PlayCinematic(void);
extern void CL_ServerStatus_f(void);
extern void Cmd_RemoveCommand(void);
extern void DObjGetLodForDist(void);
extern void DObjGetLodOutDist(void);
extern void Dvar_EnumToString(void);
extern void Dvar_RegisterBool(void);
extern void Dvar_RegisterEnum(void);
extern void Dvar_RegisterVec2(void);
extern void Dvar_RegisterVec3(void);
extern void Dvar_RegisterVec4(void);
extern void Dvar_SetIntByName(void);
extern void G_AnimScriptSound(void);
extern void R_AddLightToScene(void);
extern void R_ArchiveFogState(void);
extern void R_BeginDebugFrame(void);
extern void R_DrawConsoleText(void);
extern void R_GetFarPlaneDist(void);
extern void R_GetMaterialName(void);
extern void R_SaveCubemapShot(void);
extern void XModelGetBasePose(void);
extern void XModelGetMemUsage(void);
extern void XModelGetSurfaces(void);
extern void XModelSetTestLods(void);
extern void CL_GlobalServers_f(void);
extern void CL_PlayCinematic_f(void);
extern void Com_FindSoundAlias(void);
extern void DObjGetNumSurfaces(void);
extern void DObjGetSurfaceName(void);
extern void Dvar_ClearModified(void);
extern void Dvar_RegisterColor(void);
extern void Dvar_RegisterFloat(void);
extern void Dvar_SetBoolByName(void);
extern void Dvar_SetFromString(void);
extern void Dvar_SetVec2ByName(void);
extern void Dvar_SetVec3ByName(void);
extern void Dvar_SetVec4ByName(void);
extern void FS_FOpenFileByMode(void);
extern void Hunk_AllocInternal(void);
extern void Material_Duplicate(void);
extern void Material_IsDefault(void);
extern void R_AddCmdDrawSprite(void);
extern void R_AddCmdSaveScreen(void);
extern void R_BeginCubemapShot(void);
extern void R_ConsoleTextWidth(void);
extern void R_LocateDebugLines(void);
extern void R_RegisterRawImage(void);
extern void R_SyncRenderThread(void);
extern void CIN_UploadCinematic(void);
extern void Dvar_RegisterString(void);
extern void Dvar_SetColorByName(void);
extern void Dvar_SetFloatByName(void);
extern void R_AddCmdClearScreen(void);
extern void R_AddCmdDrawQuadPic(void);
extern void R_AddCmdSetViewport(void);
extern void R_EndDelayedDrawing(void);
extern void XModelGetLodForDist(void);
extern void XModelGetLodOutDist(void);
extern void DObjGetAllocSkelSize(void);
extern void DObjGetRotTransArray(void);
extern void Dvar_SetStringByName(void);
extern void R_LocateDebugStrings(void);
extern void Sys_HideSplashWindow(void);
extern void Sys_LoadingKeepAlive(void);
extern void Sys_ShowSplashWindow(void);
extern void XModelGetSurfaceName(void);
extern void noise_codebook_quant(void);
extern void Com_SaveDvarsToBuffer(void);
extern void Dvar_ChangeResetValue(void);
extern void Dvar_GetVariantString(void);
extern void Dvar_IsAtDefaultValue(void);
extern void Dvar_UnregisterSystem(void);
extern void Dvar_UpdateEnumDomain(void);
extern void Hunk_AllocXAnimClient(void);
extern void RB_IsGpuFenceFinished(void);
extern void R_AbortRenderCommands(void);
extern void R_BeginDelayedDrawing(void);
extern void R_DObjReplaceMaterial(void);
extern void R_DefaultVertexFrames(void);
extern void R_FinishLoadingModels(void);
extern void R_IssueDelayedDrawing(void);
extern void R_NormalizedTextScale(void);
extern void R_RegisterInlineModel(void);
extern void R_SetSunLightOverride(void);
extern void Sys_DirectXFatalError(void);
extern void XModelGetBasePoseBone(void);
extern void Com_SafeClientDObjFree(void);
extern void Com_SafeServerDObjFree(void);
extern void RB_AdaptiveGpuSyncWait(void);
extern void R_AddCmdDrawStretchPic(void);
extern void R_AddCmdDrawStretchRaw(void);
extern void R_DObjGetSurfMaterials(void);
extern void R_FreeImageAllocations(void);
extern void R_IsMaterialRefractive(void);
extern void SEH_ReadCharFromString(void);
extern void CL_UpdateLevelHunkUsage(void);
extern void Com_LoadDvarsFromBuffer(void);
extern void Hunk_AllocAlignInternal(void);
extern void Hunk_AllocXAnimPrecache(void);
extern void Material_RegisterHandle(void);
extern void R_AddCmdDrawTextInSpace(void);
extern void R_GetMinSpecImageMemory(void);
extern void R_ResetImageAllocations(void);
extern void R_ResetSunLightOverride(void);
extern void DObjSkelAreBonesUpToDate(void);
extern void Dvar_SetFromStringByName(void);
extern void R_AddCmdBlendSavedScreen(void);
extern void R_AddCmdSetMaterialColor(void);
extern void DObjCompleteHierarchyBits(void);
extern void R_GetIgnorePrecacheErrors(void);
extern void R_SetIgnorePrecacheErrors(void);
extern void R_StaticModelCacheFlush_f(void);
extern void R_StaticModelCacheStats_f(void);
extern void R_AddCmdDrawTextWithCursor(void);
extern void R_GetMaterialSubimageCount(void);
extern void R_LightingFromCubemapShots(void);
extern void R_ResetSunLightParseParams(void);
extern void speex_default_user_handler(void);
extern void CL_GetHudMsgIconMaterialName(void);
extern void R_AddCmdDrawStretchPicRotate(void);
extern void R_Cmd_ReloadMaterialTextures(void);
extern void R_InterpretSunLightParseParams(void);
extern void Com_WriteLocalizedSoundAliasFiles(void);
extern void DObjBad(void);
extern void FS_Read(void);
extern void MT_Free(void);
extern void Cmd_Argc(void);
extern void Cmd_Argv(void);
extern void FS_Write(void);
extern void R_SetFog(void);
extern void CL_Ping_f(void);
extern void CL_Rcon_f(void);
extern void FS_Path_f(void);
extern void XModelBad(void);
extern void __ZN10CVAOPacket10sVAOStatusE(void);
extern void __ZN10CVAOPacket14sCurrentPacketE(void);
extern void __ZN10CVAOPacket14sGenericPacketE(void);
extern void __ZN13COpenGLMatrix9sIdentityE(void);
extern void __ZN15CDirect3DDevice28mNeedsVertexShaderValidationE(void);
extern void __ZN15CDirect3DDevice29mNeedsRasterizationValidationE(void);
extern void __ZN15CDirect3DDevice30mNeedsTransformationValidationE(void);
extern void __ZN6CFence15sUnusedFenceIDsE(void);
extern void __ZN7COpenGL11sFrameCountE(void);
extern void __ZN7COpenGL14sShowTextureIDE(void);
extern void __ZN7COpenGL7sOpenGLE(void);
extern void __ZN7COpenGL9sDrawFlagE(void);
extern void __ZTI14COpenGLTexture(void);
extern void __ZTI17IDirect3DTexture9(void);
extern void __ZTV10COpenGLVAO(void);
extern void __ZTV11CColorArray(void);
extern void __ZTV12CNormalArray(void);
extern void __ZTV12CVertexArray(void);
extern void __ZTV14COpenGLTexture(void);
extern void __ZTV14CTexCoordArray(void);
extern void __ZTV15CCacheInfoBlock(void);
extern void __ZTV15CColorConverter(void);
extern void __ZTV17IDirect3DTexture9(void);
extern void __ZTV18IDirect3DResource9(void);
extern void __ZTV20CSecondaryColorArray(void);
extern void __ZTV21IDirect3DBaseTexture9(void);
extern void __ZTV21IDirect3DCubeTexture9(void);
extern void __ZTV22CVAOPacketProgrammable(void);
extern void __ZTV22IDirect3DVertexShader9(void);
extern void __ZTV23CVAOPacketFixedFunction(void);
extern void __ZTV23IDirect3DVolumeTexture9(void);
extern void __ZTV5Flash(void);
extern void __ZTV7CBaseVA(void);
extern void __ZTV8IUnknown(void);
extern void alwaysfails(void);
extern void backEnd(void);
extern void backEndData(void);
extern void bg_aimSpreadMoveSpeedThreshold(void);
extern void bg_bobAmplitudeDucked(void);
extern void bg_bobAmplitudeProne(void);
extern void bg_bobAmplitudeStanding(void);
extern void bg_bobMax(void);
extern void bg_fallDamageMaxHeight(void);
extern void bg_fallDamageMinHeight(void);
extern void bg_foliagesnd_fastinterval(void);
extern void bg_foliagesnd_maxspeed(void);
extern void bg_foliagesnd_minspeed(void);
extern void bg_foliagesnd_resetinterval(void);
extern void bg_foliagesnd_slowinterval(void);
extern void bg_iNumWeapons(void);
extern void bg_itemlist(void);
extern void bg_ladder_yawcap(void);
extern void bg_numItems(void);
extern void bg_prone_yawcap(void);
extern void bg_swingSpeed(void);
extern void bgs(void);
extern void bulletPriorityMap(void);
extern void cg(void);
extern void cgDC(void);
extern void cg_blood(void);
extern void cg_brass(void);
extern void cg_centerPrintY(void);
extern void cg_centertime(void);
extern void cg_chatHeight(void);
extern void cg_chatTime(void);
extern void cg_connectionIconSize(void);
extern void cg_constantSizeHeadIcons(void);
extern void cg_crosshairAlpha(void);
extern void cg_crosshairAlphaMin(void);
extern void cg_crosshairDynamic(void);
extern void cg_crosshairEnemyColor(void);
extern void cg_cursorHints(void);
extern void cg_debugEvents(void);
extern void cg_debugPosition(void);
extern void cg_descriptiveText(void);
extern void cg_draw2D(void);
extern void cg_drawBreathHint(void);
extern void cg_drawCrosshair(void);
extern void cg_drawCrosshairNames(void);
extern void cg_drawCrosshairNamesPosX(void);
extern void cg_drawCrosshairNamesPosY(void);
extern void cg_drawFPS(void);
extern void cg_drawGameMessages(void);
extern void cg_drawGun(void);
extern void cg_drawHealth(void);
extern void cg_drawLagometer(void);
extern void cg_drawMantleHint(void);
extern void cg_drawMaterial(void);
extern void cg_drawScriptUsage(void);
extern void cg_drawSnapshot(void);
extern void cg_drawSoundOverlay(void);
extern void cg_drawTurretCrosshair(void);
extern void cg_dumpAnims(void);
extern void cg_entities(void);
extern void cg_errorDecay(void);
extern void cg_footsteps(void);
extern void cg_fov(void);
extern void cg_fovMin(void);
extern void cg_fovScale(void);
extern void cg_gun_move_f(void);
extern void cg_gun_move_minspeed(void);
extern void cg_gun_move_r(void);
extern void cg_gun_move_rate(void);
extern void cg_gun_move_u(void);
extern void cg_gun_ofs_f(void);
extern void cg_gun_ofs_r(void);
extern void cg_gun_ofs_u(void);
extern void cg_gun_x(void);
extern void cg_gun_y(void);
extern void cg_gun_z(void);
extern void cg_headIconMinScreenRadius(void);
extern void cg_hintFadeTime(void);
extern void cg_hudChatPosition(void);
extern void cg_hudCompassMaxRange(void);
extern void cg_hudCompassMinRadius(void);
extern void cg_hudCompassMinRange(void);
extern void cg_hudCompassSize(void);
extern void cg_hudCompassSoundPingFadeTime(void);
extern void cg_hudCompassSpringyPointers(void);
extern void cg_hudDamageIconHeight(void);
extern void cg_hudDamageIconInScope(void);
extern void cg_hudDamageIconOffset(void);
extern void cg_hudDamageIconTime(void);
extern void cg_hudDamageIconWidth(void);
extern void cg_hudGrenadeIconHeight(void);
extern void cg_hudGrenadeIconInScope(void);
extern void cg_hudGrenadeIconMaxHeight(void);
extern void cg_hudGrenadeIconMaxRange(void);
extern void cg_hudGrenadeIconOffset(void);
extern void cg_hudGrenadeIconWidth(void);
extern void cg_hudGrenadePointerHeight(void);
extern void cg_hudGrenadePointerPivot(void);
extern void cg_hudGrenadePointerPulseFreq(void);
extern void cg_hudGrenadePointerPulseMax(void);
extern void cg_hudGrenadePointerPulseMin(void);
extern void cg_hudGrenadePointerWidth(void);
extern void cg_hudObjectiveMaxRange(void);
extern void cg_hudObjectiveMinAlpha(void);
extern void cg_hudProneY(void);
extern void cg_hudSayPosition(void);
extern void cg_hudStanceFlash(void);
extern void cg_hudStanceHintPrints(void);
extern void cg_items(void);
extern void cg_marks(void);
extern void cg_marksLimit(void);
extern void cg_minicon(void);
extern void cg_nopredict(void);
extern void cg_paused(void);
extern void cg_predictItems(void);
extern void cg_scoreboardBannerHeight(void);
extern void cg_scoreboardScrollStep(void);
extern void cg_scriptIconSize(void);
extern void cg_shock_mouse(void);
extern void cg_shock_mouse_fadeTime(void);
extern void cg_shock_mouse_maxpitchspeed(void);
extern void cg_shock_mouse_maxyawspeed(void);
extern void cg_shock_mouse_sensitivityscale(void);
extern void cg_shock_screenBlendFadeTime(void);
extern void cg_shock_screenBlendTime(void);
extern void cg_shock_sound(void);
extern void cg_shock_soundDryLevel(void);
extern void cg_shock_soundFadeInTime(void);
extern void cg_shock_soundFadeOutTime(void);
extern void cg_shock_soundLoopEndDelay(void);
extern void cg_shock_soundLoopFadeTime(void);
extern void cg_shock_soundModEndDelay(void);
extern void cg_shock_soundRoomType(void);
extern void cg_shock_soundWetLevel(void);
extern void cg_shock_viewKickPeriod(void);
extern void cg_shock_viewKickRadius(void);
extern void cg_shock_volume_announcer(void);
extern void cg_shock_volume_auto(void);
extern void cg_shock_volume_auto2d(void);
extern void cg_shock_volume_body(void);
extern void cg_shock_volume_item(void);
extern void cg_shock_volume_local(void);
extern void cg_shock_volume_menu(void);
extern void cg_shock_volume_music(void);
extern void cg_shock_volume_shellshock(void);
extern void cg_shock_volume_voice(void);
extern void cg_shock_volume_weapon(void);
extern void cg_showmiss(void);
extern void cg_subtitleCharHeight(void);
extern void cg_subtitlePosX(void);
extern void cg_subtitlePosY(void);
extern void cg_subtitles(void);
extern void cg_synchronousClients(void);
extern void cg_teamChatsOnly(void);
extern void cg_thirdPerson(void);
extern void cg_thirdPersonAngle(void);
extern void cg_thirdPersonRange(void);
extern void cg_tracerChance(void);
extern void cg_tracerLength(void);
extern void cg_tracerScale(void);
extern void cg_tracerScaleDistRange(void);
extern void cg_tracerScaleMinDist(void);
extern void cg_tracerSpeed(void);
extern void cg_tracerWidth(void);
extern void cg_viewsize(void);
extern void cg_voiceIconSize(void);
extern void cg_weaponCycleDelay(void);
extern void cg_weapons(void);
extern void cg_youInKillCamSize(void);
extern void cgs(void);
extern void chatField(void);
extern void chat_team(void);
extern void cl(void);
extern void cl_activeAction(void);
extern void cl_anglespeedkey(void);
extern void cl_bypassMouseInput(void);
extern void cl_cdkey(void);
extern void cl_cdkeychecksum(void);
extern void cl_connectedToPureServer(void);
extern void cl_freelook(void);
extern void cl_freezeDemo(void);
extern void cl_inGameVideo(void);
extern void cl_maxpackets(void);
extern void cl_mouseAccel(void);
extern void cl_nodelta(void);
extern void cl_noprint(void);
extern void cl_packetdup(void);
extern void cl_paused(void);
extern void cl_pinglist(void);
extern void cl_pitchspeed(void);
extern void cl_sensitivity(void);
extern void cl_serverStatusResendTime(void);
extern void cl_showMouseRate(void);
extern void cl_showSend(void);
extern void cl_showServerCommands(void);
extern void cl_showTimeDelta(void);
extern void cl_shownet(void);
extern void cl_shownuments(void);
extern void cl_talking(void);
extern void cl_voice(void);
extern void cl_yawspeed(void);
extern void clc(void);
extern void clients(void);
extern void cls(void);
extern void cm(void);
extern void colorBlack(void);
extern void colorBlue(void);
extern void colorCyan(void);
extern void colorGreen(void);
extern void colorLtCyan(void);
extern void colorLtGrey(void);
extern void colorLtYellow(void);
extern void colorMagenta(void);
extern void colorMdCyan(void);
extern void colorRed(void);
extern void colorWhite(void);
extern void colorYellow(void);
extern void com_dedicated(void);
extern void com_developer(void);
extern void com_errorEntered(void);
extern void com_expectedHunkUsage(void);
extern void com_fileAccessed(void);
extern void com_fixedConsolePosition(void);
extern void com_frameTime(void);
extern void com_logfile(void);
extern void com_playerProfile(void);
extern void com_statmon(void);
extern void com_sv_running(void);
extern void com_timescaleValue(void);
extern void com_viewlog(void);
extern void current_audioCallback(void);
extern void developer(void);
extern void dvarCount(void);
extern void dvar_modifiedFlags(void);
extern void dx(void);
extern void dxState(void);
extern void effectActiveCountBolt(void);
extern void effectActiveCountNonBolt(void);
extern void entityHandlers(void);
extern void eventnames(void);
extern void frame_msec(void);
extern void friction(void);
extern void frontEndDataOut(void);
extern void fs_basepath(void);
extern void fs_cdpath(void);
extern void fs_checksumFeed(void);
extern void fs_copyfiles(void);
extern void fs_debug(void);
extern void fs_fakeChkSum(void);
extern void fs_gamedir(void);
extern void fs_homepath(void);
extern void fs_ignoreLocalized(void);
extern void fs_numServerIwds(void);
extern void fs_numServerReferencedIwds(void);
extern void fs_restrict(void);
extern void fs_searchpaths(void);
extern void fs_serverIwdNames(void);
extern void fs_serverIwds(void);
extern void fs_serverReferencedIwdNames(void);
extern void fs_serverReferencedIwds(void);
extern void fsh(void);
extern void fxSchedulers(void);
extern void fx_camera_valid(void);
extern void fx_count(void);
extern void fx_cull(void);
extern void fx_debug(void);
extern void fx_debugBolt(void);
extern void fx_draw(void);
extern void fx_enable(void);
extern void fx_freeze(void);
extern void fx_sort(void);
extern void fx_visMinTraceDist(void);
extern void gConsoleRunning(void);
extern void g_CurrentGenericPacket(void);
extern void g_EndPos(void);
extern void g_InhibitCopy(void);
extern void g_InhibitOpenGLErrors(void);
extern void g_NoScriptSpam(void);
extern void g_NoTextureID(void);
extern void g_RenderToShadowCookie(void);
extern void g_TotalFilterPasses(void);
extern void g_VAOID(void);
extern void g_WarmOff(void);
extern void g_allowVote(void);
extern void g_antilag(void);
extern void g_banIPs(void);
extern void g_cheats(void);
extern void g_clonePlayerMaxVelocity(void);
extern void g_consoleField(void);
extern void g_console_char_height(void);
extern void g_console_field_width(void);
extern void g_current_bandwidth_setting(void);
extern void g_deadChat(void);
extern void g_debugDamage(void);
extern void g_debugLocDamage(void);
extern void g_dedicated(void);
extern void g_disableRendering(void);
extern void g_dropForwardSpeed(void);
extern void g_dropUpSpeedBase(void);
extern void g_dropUpSpeedRand(void);
extern void g_editingField(void);
extern void g_effectVisArray(void);
extern void g_effectVisArrayCount(void);
extern void g_encoder_samplerate(void);
extern void g_entities(void);
extern void g_frame_size(void);
extern void g_friendlyNameDist(void);
extern void g_friendlyfireDist(void);
extern void g_gametype(void);
extern void g_gravity(void);
extern void g_hudelems(void);
extern void g_inactivity(void);
extern void g_knockback(void);
extern void g_mantleBlockTimeBuffer(void);
extern void g_maxDroppedWeapons(void);
extern void g_maxclients(void);
extern void g_motd(void);
extern void g_oldVoting(void);
extern void g_password(void);
extern void g_playerCollisionEjectSpeed(void);
extern void g_qport(void);
extern void g_rendererExists(void);
extern void g_scr_data(void);
extern void g_skinBuffers(void);
extern void g_smoothClients(void);
extern void g_snd(void);
extern void g_special(void);
extern void g_speed(void);
extern void g_synchronousClients(void);
extern void g_traceThreadInfo(void);
extern void g_useholdspawndelay(void);
extern void g_useholdtime(void);
extern void g_voiceChatTalkingDuration(void);
extern void g_waitingForServer(void);
extern void g_weaponAmmoPools(void);
extern void g_wv(void);
extern void gameInitialized(void);
extern void hintStrings(void);
extern void historyEditLines(void);
extern void hud_fade_ammodisplay(void);
extern void hud_fade_compass(void);
extern void hud_fade_healthbar(void);
extern void hud_fade_offhand(void);
extern void hud_fade_stance(void);
extern void hud_health_startpulse_injured(void);
extern void inertiaAngle(void);
extern void inertiaDebug(void);
extern void inertiaMax(void);
extern void infoParms(void);
extern void keys(void);
extern void legacyHacks(void);
extern void legacyHacksArray(void);
extern void level(void);
extern void level_bgs(void);
extern void loc_language(void);
extern void loc_warnings(void);
extern void loc_warningsAsErrors(void);
extern void m_filter(void);
extern void m_forward(void);
extern void m_pitch(void);
extern void m_side(void);
extern void m_yaw(void);
extern void modNames(void);
extern void net_lanauthorize(void);
extern void net_profile(void);
extern void net_showprofile(void);
extern void nextdemo(void);
extern void nextmap(void);
extern void playerMaxs(void);
extern void playerMins(void);
extern void player_adsExitDelay(void);
extern void player_backSpeedScale(void);
extern void player_breath_fire_delay(void);
extern void player_breath_gasp_lerp(void);
extern void player_breath_gasp_scale(void);
extern void player_breath_gasp_time(void);
extern void player_breath_hold_lerp(void);
extern void player_breath_hold_time(void);
extern void player_breath_snd_delay(void);
extern void player_breath_snd_lerp(void);
extern void player_dmgtimer_maxTime(void);
extern void player_dmgtimer_minScale(void);
extern void player_dmgtimer_stumbleTime(void);
extern void player_dmgtimer_timePerPoint(void);
extern void player_footstepsThreshhold(void);
extern void player_meleeHeight(void);
extern void player_meleeRange(void);
extern void player_meleeWidth(void);
extern void player_moveThreshhold(void);
extern void player_scopeExitOnDamage(void);
extern void player_spectateSpeedScale(void);
extern void player_strafeSpeedScale(void);
extern void player_toggleBinoculars(void);
extern void player_turnAnims(void);
extern void player_view_pitch_down(void);
extern void player_view_pitch_up(void);
extern void pmoveHandlers(void);
extern void privateEffectActiveCountBolt(void);
extern void privateEffectActiveCountNonBolt(void);
extern void r_aaAlpha(void);
extern void r_aaSamples(void);
extern void r_anisotropy(void);
extern void r_aspectRatio(void);
extern void r_blur(void);
extern void r_clearColor(void);
extern void r_colorMap(void);
extern void r_cosinePowerMapShift(void);
extern void r_debugEntCounts(void);
extern void r_debugShader(void);
extern void r_depthPrepassModels(void);
extern void r_displayRefresh(void);
extern void r_distortion(void);
extern void r_dlightLimit(void);
extern void r_drawBModels(void);
extern void r_drawDecals(void);
extern void r_drawEntities(void);
extern void r_drawPrimCap(void);
extern void r_drawPrimFloor(void);
extern void r_drawSModels(void);
extern void r_drawSun(void);
extern void r_drawWater(void);
extern void r_drawWorld(void);
extern void r_drawXModels(void);
extern void r_fog(void);
extern void r_forceLod(void);
extern void r_fullbright(void);
extern void r_gamma(void);
extern void r_glow(void);
extern void r_glowBloomCutoff(void);
extern void r_glowBloomDesaturation(void);
extern void r_glowBloomIntensity(void);
extern void r_glowRadius(void);
extern void r_glowSkyBleedIntensity(void);
extern void r_gpuSync(void);
extern void r_highLodDist(void);
extern void r_ignoreHwGamma(void);
extern void r_lightMap(void);
extern void r_lightTweakAmbient(void);
extern void r_lightTweakAmbientColor(void);
extern void r_lightTweakDiffuseFraction(void);
extern void r_lightTweakSunColor(void);
extern void r_lightTweakSunDiffuseColor(void);
extern void r_lightTweakSunDirection(void);
extern void r_lightTweakSunLight(void);
extern void r_lockPvs(void);
extern void r_lodBias(void);
extern void r_lodScale(void);
extern void r_logFile(void);
extern void r_lowLodDist(void);
extern void r_lowestLodDist(void);
extern void r_mediumLodDist(void);
extern void r_mode(void);
extern void r_multiGpu(void);
extern void r_norefresh(void);
extern void r_normalMap(void);
extern void r_objectiveColorDx7Max(void);
extern void r_objectiveColorDx7Min(void);
extern void r_optimizeLightmaps(void);
extern void r_optimizeXModels(void);
extern void r_outdoorAwayBias(void);
extern void r_outdoorDownBias(void);
extern void r_outdoorFeather(void);
extern void r_overbrightBits(void);
extern void r_picmip(void);
extern void r_picmip_bump(void);
extern void r_picmip_manual(void);
extern void r_picmip_spec(void);
extern void r_polygonOffsetBias(void);
extern void r_polygonOffsetScale(void);
extern void r_portalBevels(void);
extern void r_portalBevelsOnly(void);
extern void r_portalFineCull(void);
extern void r_portalMinClipArea(void);
extern void r_portalWalkLimit(void);
extern void r_railCoreWidth(void);
extern void r_rendererInUse(void);
extern void r_rendererPreference(void);
extern void r_showFbColorDebug(void);
extern void r_showGroundLit(void);
extern void r_showLightGrid(void);
extern void r_showMissingLightGrid(void);
extern void r_showPortals(void);
extern void r_showSModelNames(void);
extern void r_showSurfCounts(void);
extern void r_showTriCounts(void);
extern void r_showTris(void);
extern void r_showVertCounts(void);
extern void r_singleCell(void);
extern void r_skinCache(void);
extern void r_skipBackEnd(void);
extern void r_skipPvs(void);
extern void r_smc_enable(void);
extern void r_specularColorScale(void);
extern void r_specularMap(void);
extern void r_sun_from_dvars(void);
extern void r_swapInterval(void);
extern void r_testFill(void);
extern void r_testFillEnable(void);
extern void r_testTransform(void);
extern void r_textureMode(void);
extern void r_vc_makelog(void);
extern void r_vc_showlog(void);
extern void r_xdebug(void);
extern void r_zfar(void);
extern void r_znear(void);
extern void r_znear_depthhack(void);
extern void rcon_password(void);
extern void re(void);
extern void rg(void);
extern void rgp(void);
extern void ri(void);
extern void riflePriorityMap(void);
extern void s_sundvars(void);
extern void sc_blur(void);
extern void sc_enable(void);
extern void sc_showDebug(void);
extern void scene(void);
extern void scrAnimPub(void);
extern void scrCompileGlob(void);
extern void scrCompilePub(void);
extern void scrMemTreePub(void);
extern void scrParserPub(void);
extern void scrVarPub(void);
extern void scrVmPub(void);
extern void scr_const(void);
extern void sharedUiInfo(void);
extern void singleClientEvents(void);
extern void snd_bits(void);
extern void snd_enableReverb(void);
extern void snd_errorOnMissing(void);
extern void snd_khz(void);
extern void snd_roomStrings(void);
extern void snd_stereo(void);
extern void snd_touchStreamFilesOnLoad(void);
extern void sortedDvars(void);
extern void speex_nb_mode(void);
extern void speex_uwb_mode(void);
extern void speex_wb_mode(void);
extern void stopspeed(void);
extern void sunFlareArray(void);
extern void sv(void);
extern void sv_allowAnonymous(void);
extern void sv_allowDownload(void);
extern void sv_allowedClan1(void);
extern void sv_allowedClan2(void);
extern void sv_cheats(void);
extern void sv_debugRate(void);
extern void sv_debugReliableCmds(void);
extern void sv_disableClientConsole(void);
extern void sv_floodProtect(void);
extern void sv_fps(void);
extern void sv_gametype(void);
extern void sv_hostname(void);
extern void sv_iwdNames(void);
extern void sv_iwds(void);
extern void sv_kickBanTime(void);
extern void sv_mapRotation(void);
extern void sv_mapRotationCurrent(void);
extern void sv_mapname(void);
extern void sv_maxPing(void);
extern void sv_maxRate(void);
extern void sv_maxclients(void);
extern void sv_minPing(void);
extern void showpackets(void);
extern void sv_packet_info(void);
extern void sv_padPackets(void);
extern void sv_paused(void);
extern void sv_privateClients(void);
extern void sv_privatePassword(void);
extern void sv_pure(void);
extern void sv_reconnectlimit(void);
extern void sv_referencedIwdNames(void);
extern void sv_referencedIwds(void);
extern void sv_serverId_value(void);
extern void sv_serverid(void);
extern void sv_showAverageBPS(void);
extern void sv_showCommands(void);
extern void sv_timeout(void);
extern void sv_voice(void);
extern void sv_voiceQuality(void);
extern void sv_zombietime(void);
extern void svs(void);
extern void tess(void);
extern void theFxHelper(void);
extern void theFxScheduler(void);
extern void updateScreenCalled(void);
extern void var_typename(void);
extern void vbr_nb_thresh(void);
extern void vec3_colorintensity(void);
extern void vec3_origin(void);
extern void vidConfig(void);
extern void vid_xpos(void);
extern void vid_ypos(void);
extern void voice_current_scaler(void);
extern void voice_current_voicelevel(void);
extern void voice_deadChat(void);
extern void voice_global(void);
extern void voice_localEcho(void);
extern void zcalloc(void);
extern void zcfree(void);
void * const imp_Com_Error = (void *)(uintptr_t)Com_Error;
void * const imp_FS_FreeFile = (void *)(uintptr_t)FS_FreeFile;
void * const imp_FS_FreeFileList = (void *)(uintptr_t)FS_FreeFileList;
void * const imp_FS_ListFiles = (void *)(uintptr_t)FS_ListFiles;
void * const imp_FS_ReadFile = (void *)(uintptr_t)FS_ReadFile;
void * const imp_Hunk_AllocateTempMemoryHighInternal = (void *)(uintptr_t)Hunk_AllocateTempMemoryHighInternal;
void * const imp_Hunk_AllocateTempMemoryInternal = (void *)(uintptr_t)Hunk_AllocateTempMemoryInternal;
void * const imp_Hunk_ClearTempMemory = (void *)(uintptr_t)Hunk_ClearTempMemory;
void * const imp_Hunk_ClearTempMemoryHigh = (void *)(uintptr_t)Hunk_ClearTempMemoryHigh;
void * const imp_Hunk_FreeTempMemory = (void *)(uintptr_t)Hunk_FreeTempMemory;
void * const imp_Hunk_OverrideDataForFile = (void *)(uintptr_t)Hunk_OverrideDataForFile;
void * const imp_I_strcmp = (void *)(uintptr_t)I_strcmp;
void * const imp_I_stricmp = (void *)(uintptr_t)I_stricmp;
void * const imp_Z_FreeInternal = (void *)(uintptr_t)Z_FreeInternal;
void * const imp_Z_MallocInternal = (void *)(uintptr_t)Z_MallocInternal;
void * const imp_Z_VirtualCommitInternal = (void *)(uintptr_t)Z_VirtualCommitInternal;
void * const imp_Z_VirtualDecommitInternal = (void *)(uintptr_t)Z_VirtualDecommitInternal;
void * const imp_Z_VirtualFreeInternal = (void *)(uintptr_t)Z_VirtualFreeInternal;
void * const imp_Z_VirtualReserveInternal = (void *)(uintptr_t)Z_VirtualReserveInternal;
void * const imp_Com_GetBsp = (void *)(uintptr_t)Com_GetBsp;
void * const imp_DObjCreate = (void *)(uintptr_t)DObjCreate;
void * const imp_Dvar_Reset = (void *)(uintptr_t)Dvar_Reset;
void * const imp_R_AddPlume = (void *)(uintptr_t)R_AddPlume;
void * const imp_R_DrawText = (void *)(uintptr_t)R_DrawText;
void * const imp_R_EndFrame = (void *)(uintptr_t)R_EndFrame;
void * const imp_CM_BoxTrace = (void *)(uintptr_t)CM_BoxTrace;
void * const imp_CM_SaveLump = (void *)(uintptr_t)CM_SaveLump;
void * const imp_Dvar_GetInt = (void *)(uintptr_t)Dvar_GetInt;
void * const imp_Dvar_SetInt = (void *)(uintptr_t)Dvar_SetInt;
void * const imp_R_ClearFogs = (void *)(uintptr_t)R_ClearFogs;
void * const imp_R_LoadWorld = (void *)(uintptr_t)R_LoadWorld;
void * const imp_R_SwitchFog = (void *)(uintptr_t)R_SwitchFog;
void * const imp_R_TextWidth = (void *)(uintptr_t)R_TextWidth;
void * const imp_CL_Connect_f = (void *)(uintptr_t)CL_Connect_f;
void * const imp_DObjCalcAnim = (void *)(uintptr_t)DObjCalcAnim;
void * const imp_DObjCalcSkel = (void *)(uintptr_t)DObjCalcSkel;
void * const imp_DObjGetModel = (void *)(uintptr_t)DObjGetModel;
void * const imp_DObjNumBones = (void *)(uintptr_t)DObjNumBones;
void * const imp_DObjSetModel = (void *)(uintptr_t)DObjSetModel;
void * const imp_Dvar_GetBool = (void *)(uintptr_t)Dvar_GetBool;
void * const imp_Dvar_SetBool = (void *)(uintptr_t)Dvar_SetBool;
void * const imp_Dvar_SetVec2 = (void *)(uintptr_t)Dvar_SetVec2;
void * const imp_Dvar_SetVec3 = (void *)(uintptr_t)Dvar_SetVec3;
void * const imp_Dvar_SetVec4 = (void *)(uintptr_t)Dvar_SetVec4;
void * const imp_FS_WriteFile = (void *)(uintptr_t)FS_WriteFile;
void * const imp_G_FreeEntity = (void *)(uintptr_t)G_FreeEntity;
void * const imp_RB_GpuWaited = (void *)(uintptr_t)RB_GpuWaited;
void * const imp_R_BeginFrame = (void *)(uintptr_t)R_BeginFrame;
void * const imp_R_ClearScene = (void *)(uintptr_t)R_ClearScene;
void * const imp_R_TextHeight = (void *)(uintptr_t)R_TextHeight;
void * const imp_SV_XModelGet = (void *)(uintptr_t)SV_XModelGet;
void * const imp_DObjGetBounds = (void *)(uintptr_t)DObjGetBounds;
void * const imp_Dvar_GetFloat = (void *)(uintptr_t)Dvar_GetFloat;
void * const imp_Dvar_SetColor = (void *)(uintptr_t)Dvar_SetColor;
void * const imp_Dvar_SetFloat = (void *)(uintptr_t)Dvar_SetFloat;
void * const imp_FS_FCloseFile = (void *)(uintptr_t)FS_FCloseFile;
void * const imp_FS_FileExists = (void *)(uintptr_t)FS_FileExists;
void * const imp_FS_FullPath_f = (void *)(uintptr_t)FS_FullPath_f;
void * const imp_R_ClearFlares = (void *)(uintptr_t)R_ClearFlares;
void * const imp_R_Cmd_LoadSun = (void *)(uintptr_t)R_Cmd_LoadSun;
void * const imp_R_Cmd_SaveSun = (void *)(uintptr_t)R_Cmd_SaveSun;
void * const imp_R_ImageList_f = (void *)(uintptr_t)R_ImageList_f;
void * const imp_R_ModelBounds = (void *)(uintptr_t)R_ModelBounds;
void * const imp_R_RenderScene = (void *)(uintptr_t)R_RenderScene;
void * const imp_R_SetCullDist = (void *)(uintptr_t)R_SetCullDist;
void * const imp_UI_OpenMenu_f = (void *)(uintptr_t)UI_OpenMenu_f;
void * const imp_XModelGetName = (void *)(uintptr_t)XModelGetName;
void * const imp_Cmd_AddCommand = (void *)(uintptr_t)Cmd_AddCommand;
void * const imp_DObjCreateSkel = (void *)(uintptr_t)DObjCreateSkel;
void * const imp_DObjGetSurface = (void *)(uintptr_t)DObjGetSurface;
void * const imp_Dvar_GetString = (void *)(uintptr_t)Dvar_GetString;
void * const imp_Dvar_SetString = (void *)(uintptr_t)Dvar_SetString;
void * const imp_RB_UpdateColor = (void *)(uintptr_t)RB_UpdateColor;
void * const imp_R_PickMaterial = (void *)(uintptr_t)R_PickMaterial;
void * const imp_R_RegisterFont = (void *)(uintptr_t)R_RegisterFont;
void * const imp_R_SetLodOrigin = (void *)(uintptr_t)R_SetLodOrigin;
void * const imp_UI_CloseMenu_f = (void *)(uintptr_t)UI_CloseMenu_f;
void * const imp_XModelGetFlags = (void *)(uintptr_t)XModelGetFlags;
void * const imp_XModelGetSkins = (void *)(uintptr_t)XModelGetSkins;
void * const imp_XModelNumBones = (void *)(uintptr_t)XModelNumBones;
void * const imp_XModelPrecache = (void *)(uintptr_t)XModelPrecache;
void * const imp_CG_DObjCalcPose = (void *)(uintptr_t)CG_DObjCalcPose;
void * const imp_DObjGetBoneInfo = (void *)(uintptr_t)DObjGetBoneInfo;
void * const imp_DObjGetSurfaces = (void *)(uintptr_t)DObjGetSurfaces;
void * const imp_R_DuplicateFont = (void *)(uintptr_t)R_DuplicateFont;
void * const imp_R_EndDebugFrame = (void *)(uintptr_t)R_EndDebugFrame;
void * const imp_R_MarkFragments = (void *)(uintptr_t)R_MarkFragments;
void * const imp_R_ParseSunLight = (void *)(uintptr_t)R_ParseSunLight;
void * const imp_R_RegisterModel = (void *)(uintptr_t)R_RegisterModel;
void * const imp_R_ShutdownDebug = (void *)(uintptr_t)R_ShutdownDebug;
void * const imp_StatMon_Warning = (void *)(uintptr_t)StatMon_Warning;
void * const imp_CIN_RunCinematic = (void *)(uintptr_t)CIN_RunCinematic;
void * const imp_CL_CubemapShot_f = (void *)(uintptr_t)CL_CubemapShot_f;
void * const imp_CM_BoxSightTrace = (void *)(uintptr_t)CM_BoxSightTrace;
void * const imp_Cbuf_ExecuteText = (void *)(uintptr_t)Cbuf_ExecuteText;
void * const imp_DObjGetMatOffset = (void *)(uintptr_t)DObjGetMatOffset;
void * const imp_DObjGetNumModels = (void *)(uintptr_t)DObjGetNumModels;
void * const imp_Dvar_RegisterInt = (void *)(uintptr_t)Dvar_RegisterInt;
void * const imp_Dvar_SetModified = (void *)(uintptr_t)Dvar_SetModified;
void * const imp_FS_FOpenFileRead = (void *)(uintptr_t)FS_FOpenFileRead;
void * const imp_G_RegisterWeapon = (void *)(uintptr_t)G_RegisterWeapon;
void * const imp_R_AddPolyToScene = (void *)(uintptr_t)R_AddPolyToScene;
void * const imp_R_EndCubemapShot = (void *)(uintptr_t)R_EndCubemapShot;
void * const imp_R_GetWorldBounds = (void *)(uintptr_t)R_GetWorldBounds;
void * const imp_SCR_UpdateScreen = (void *)(uintptr_t)SCR_UpdateScreen;
void * const imp_XModelGetLodName = (void *)(uintptr_t)XModelGetLodName;
void * const imp_XModelGetNumLods = (void *)(uintptr_t)XModelGetNumLods;
void * const imp_CIN_PlayCinematic = (void *)(uintptr_t)CIN_PlayCinematic;
void * const imp_CL_ServerStatus_f = (void *)(uintptr_t)CL_ServerStatus_f;
void * const imp_Cmd_RemoveCommand = (void *)(uintptr_t)Cmd_RemoveCommand;
void * const imp_DObjGetLodForDist = (void *)(uintptr_t)DObjGetLodForDist;
void * const imp_DObjGetLodOutDist = (void *)(uintptr_t)DObjGetLodOutDist;
void * const imp_Dvar_EnumToString = (void *)(uintptr_t)Dvar_EnumToString;
void * const imp_Dvar_RegisterBool = (void *)(uintptr_t)Dvar_RegisterBool;
void * const imp_Dvar_RegisterEnum = (void *)(uintptr_t)Dvar_RegisterEnum;
void * const imp_Dvar_RegisterVec2 = (void *)(uintptr_t)Dvar_RegisterVec2;
void * const imp_Dvar_RegisterVec3 = (void *)(uintptr_t)Dvar_RegisterVec3;
void * const imp_Dvar_RegisterVec4 = (void *)(uintptr_t)Dvar_RegisterVec4;
void * const imp_Dvar_SetIntByName = (void *)(uintptr_t)Dvar_SetIntByName;
void * const imp_G_AnimScriptSound = (void *)(uintptr_t)G_AnimScriptSound;
void * const imp_R_AddLightToScene = (void *)(uintptr_t)R_AddLightToScene;
void * const imp_R_ArchiveFogState = (void *)(uintptr_t)R_ArchiveFogState;
void * const imp_R_BeginDebugFrame = (void *)(uintptr_t)R_BeginDebugFrame;
void * const imp_R_DrawConsoleText = (void *)(uintptr_t)R_DrawConsoleText;
void * const imp_R_GetFarPlaneDist = (void *)(uintptr_t)R_GetFarPlaneDist;
void * const imp_R_GetMaterialName = (void *)(uintptr_t)R_GetMaterialName;
void * const imp_R_SaveCubemapShot = (void *)(uintptr_t)R_SaveCubemapShot;
void * const imp_XModelGetBasePose = (void *)(uintptr_t)XModelGetBasePose;
void * const imp_XModelGetMemUsage = (void *)(uintptr_t)XModelGetMemUsage;
void * const imp_XModelGetSurfaces = (void *)(uintptr_t)XModelGetSurfaces;
void * const imp_XModelSetTestLods = (void *)(uintptr_t)XModelSetTestLods;
void * const imp_CL_GlobalServers_f = (void *)(uintptr_t)CL_GlobalServers_f;
void * const imp_CL_PlayCinematic_f = (void *)(uintptr_t)CL_PlayCinematic_f;
void * const imp_Com_FindSoundAlias = (void *)(uintptr_t)Com_FindSoundAlias;
void * const imp_DObjGetNumSurfaces = (void *)(uintptr_t)DObjGetNumSurfaces;
void * const imp_DObjGetSurfaceName = (void *)(uintptr_t)DObjGetSurfaceName;
void * const imp_Dvar_ClearModified = (void *)(uintptr_t)Dvar_ClearModified;
void * const imp_Dvar_RegisterColor = (void *)(uintptr_t)Dvar_RegisterColor;
void * const imp_Dvar_RegisterFloat = (void *)(uintptr_t)Dvar_RegisterFloat;
void * const imp_Dvar_SetBoolByName = (void *)(uintptr_t)Dvar_SetBoolByName;
void * const imp_Dvar_SetFromString = (void *)(uintptr_t)Dvar_SetFromString;
void * const imp_Dvar_SetVec2ByName = (void *)(uintptr_t)Dvar_SetVec2ByName;
void * const imp_Dvar_SetVec3ByName = (void *)(uintptr_t)Dvar_SetVec3ByName;
void * const imp_Dvar_SetVec4ByName = (void *)(uintptr_t)Dvar_SetVec4ByName;
void * const imp_FS_FOpenFileByMode = (void *)(uintptr_t)FS_FOpenFileByMode;
void * const imp_Hunk_AllocInternal = (void *)(uintptr_t)Hunk_AllocInternal;
void * const imp_Material_Duplicate = (void *)(uintptr_t)Material_Duplicate;
void * const imp_Material_IsDefault = (void *)(uintptr_t)Material_IsDefault;
void * const imp_R_AddCmdDrawSprite = (void *)(uintptr_t)R_AddCmdDrawSprite;
void * const imp_R_AddCmdSaveScreen = (void *)(uintptr_t)R_AddCmdSaveScreen;
void * const imp_R_BeginCubemapShot = (void *)(uintptr_t)R_BeginCubemapShot;
void * const imp_R_ConsoleTextWidth = (void *)(uintptr_t)R_ConsoleTextWidth;
void * const imp_R_LocateDebugLines = (void *)(uintptr_t)R_LocateDebugLines;
void * const imp_R_RegisterRawImage = (void *)(uintptr_t)R_RegisterRawImage;
void * const imp_R_SyncRenderThread = (void *)(uintptr_t)R_SyncRenderThread;
void * const imp_CIN_UploadCinematic = (void *)(uintptr_t)CIN_UploadCinematic;
void * const imp_Dvar_RegisterString = (void *)(uintptr_t)Dvar_RegisterString;
void * const imp_Dvar_SetColorByName = (void *)(uintptr_t)Dvar_SetColorByName;
void * const imp_Dvar_SetFloatByName = (void *)(uintptr_t)Dvar_SetFloatByName;
void * const imp_R_AddCmdClearScreen = (void *)(uintptr_t)R_AddCmdClearScreen;
void * const imp_R_AddCmdDrawQuadPic = (void *)(uintptr_t)R_AddCmdDrawQuadPic;
void * const imp_R_AddCmdSetViewport = (void *)(uintptr_t)R_AddCmdSetViewport;
void * const imp_R_EndDelayedDrawing = (void *)(uintptr_t)R_EndDelayedDrawing;
void * const imp_XModelGetLodForDist = (void *)(uintptr_t)XModelGetLodForDist;
void * const imp_XModelGetLodOutDist = (void *)(uintptr_t)XModelGetLodOutDist;
void * const imp_DObjGetAllocSkelSize = (void *)(uintptr_t)DObjGetAllocSkelSize;
void * const imp_DObjGetRotTransArray = (void *)(uintptr_t)DObjGetRotTransArray;
void * const imp_Dvar_SetStringByName = (void *)(uintptr_t)Dvar_SetStringByName;
void * const imp_R_LocateDebugStrings = (void *)(uintptr_t)R_LocateDebugStrings;
void * const imp_Sys_HideSplashWindow = (void *)(uintptr_t)Sys_HideSplashWindow;
void * const imp_Sys_LoadingKeepAlive = (void *)(uintptr_t)Sys_LoadingKeepAlive;
void * const imp_Sys_ShowSplashWindow = (void *)(uintptr_t)Sys_ShowSplashWindow;
void * const imp_XModelGetSurfaceName = (void *)(uintptr_t)XModelGetSurfaceName;
void * const imp_noise_codebook_quant = (void *)(uintptr_t)noise_codebook_quant;
void * const imp_Com_SaveDvarsToBuffer = (void *)(uintptr_t)Com_SaveDvarsToBuffer;
void * const imp_Dvar_ChangeResetValue = (void *)(uintptr_t)Dvar_ChangeResetValue;
void * const imp_Dvar_GetVariantString = (void *)(uintptr_t)Dvar_GetVariantString;
void * const imp_Dvar_IsAtDefaultValue = (void *)(uintptr_t)Dvar_IsAtDefaultValue;
void * const imp_Dvar_UnregisterSystem = (void *)(uintptr_t)Dvar_UnregisterSystem;
void * const imp_Dvar_UpdateEnumDomain = (void *)(uintptr_t)Dvar_UpdateEnumDomain;
void * const imp_Hunk_AllocXAnimClient = (void *)(uintptr_t)Hunk_AllocXAnimClient;
void * const imp_RB_IsGpuFenceFinished = (void *)(uintptr_t)RB_IsGpuFenceFinished;
void * const imp_R_AbortRenderCommands = (void *)(uintptr_t)R_AbortRenderCommands;
void * const imp_R_BeginDelayedDrawing = (void *)(uintptr_t)R_BeginDelayedDrawing;
void * const imp_R_DObjReplaceMaterial = (void *)(uintptr_t)R_DObjReplaceMaterial;
void * const imp_R_DefaultVertexFrames = (void *)(uintptr_t)R_DefaultVertexFrames;
void * const imp_R_FinishLoadingModels = (void *)(uintptr_t)R_FinishLoadingModels;
void * const imp_R_IssueDelayedDrawing = (void *)(uintptr_t)R_IssueDelayedDrawing;
void * const imp_R_NormalizedTextScale = (void *)(uintptr_t)R_NormalizedTextScale;
void * const imp_R_RegisterInlineModel = (void *)(uintptr_t)R_RegisterInlineModel;
void * const imp_R_SetSunLightOverride = (void *)(uintptr_t)R_SetSunLightOverride;
void * const imp_Sys_DirectXFatalError = (void *)(uintptr_t)Sys_DirectXFatalError;
void * const imp_XModelGetBasePoseBone = (void *)(uintptr_t)XModelGetBasePoseBone;
void * const imp_Com_SafeClientDObjFree = (void *)(uintptr_t)Com_SafeClientDObjFree;
void * const imp_Com_SafeServerDObjFree = (void *)(uintptr_t)Com_SafeServerDObjFree;
void * const imp_RB_AdaptiveGpuSyncWait = (void *)(uintptr_t)RB_AdaptiveGpuSyncWait;
void * const imp_R_AddCmdDrawStretchPic = (void *)(uintptr_t)R_AddCmdDrawStretchPic;
void * const imp_R_AddCmdDrawStretchRaw = (void *)(uintptr_t)R_AddCmdDrawStretchRaw;
void * const imp_R_DObjGetSurfMaterials = (void *)(uintptr_t)R_DObjGetSurfMaterials;
void * const imp_R_FreeImageAllocations = (void *)(uintptr_t)R_FreeImageAllocations;
void * const imp_R_IsMaterialRefractive = (void *)(uintptr_t)R_IsMaterialRefractive;
void * const imp_SEH_ReadCharFromString = (void *)(uintptr_t)SEH_ReadCharFromString;
void * const imp_CL_UpdateLevelHunkUsage = (void *)(uintptr_t)CL_UpdateLevelHunkUsage;
void * const imp_Com_LoadDvarsFromBuffer = (void *)(uintptr_t)Com_LoadDvarsFromBuffer;
void * const imp_Hunk_AllocAlignInternal = (void *)(uintptr_t)Hunk_AllocAlignInternal;
void * const imp_Hunk_AllocXAnimPrecache = (void *)(uintptr_t)Hunk_AllocXAnimPrecache;
void * const imp_Material_RegisterHandle = (void *)(uintptr_t)Material_RegisterHandle;
void * const imp_R_AddCmdDrawTextInSpace = (void *)(uintptr_t)R_AddCmdDrawTextInSpace;
void * const imp_R_GetMinSpecImageMemory = (void *)(uintptr_t)R_GetMinSpecImageMemory;
void * const imp_R_ResetImageAllocations = (void *)(uintptr_t)R_ResetImageAllocations;
void * const imp_R_ResetSunLightOverride = (void *)(uintptr_t)R_ResetSunLightOverride;
void * const imp_DObjSkelAreBonesUpToDate = (void *)(uintptr_t)DObjSkelAreBonesUpToDate;
void * const imp_Dvar_SetFromStringByName = (void *)(uintptr_t)Dvar_SetFromStringByName;
void * const imp_R_AddCmdBlendSavedScreen = (void *)(uintptr_t)R_AddCmdBlendSavedScreen;
void * const imp_R_AddCmdSetMaterialColor = (void *)(uintptr_t)R_AddCmdSetMaterialColor;
void * const imp_DObjCompleteHierarchyBits = (void *)(uintptr_t)DObjCompleteHierarchyBits;
void * const imp_R_GetIgnorePrecacheErrors = (void *)(uintptr_t)R_GetIgnorePrecacheErrors;
void * const imp_R_SetIgnorePrecacheErrors = (void *)(uintptr_t)R_SetIgnorePrecacheErrors;
void * const imp_R_StaticModelCacheFlush_f = (void *)(uintptr_t)R_StaticModelCacheFlush_f;
void * const imp_R_StaticModelCacheStats_f = (void *)(uintptr_t)R_StaticModelCacheStats_f;
void * const imp_R_AddCmdDrawTextWithCursor = (void *)(uintptr_t)R_AddCmdDrawTextWithCursor;
void * const imp_R_GetMaterialSubimageCount = (void *)(uintptr_t)R_GetMaterialSubimageCount;
void * const imp_R_LightingFromCubemapShots = (void *)(uintptr_t)R_LightingFromCubemapShots;
void * const imp_R_ResetSunLightParseParams = (void *)(uintptr_t)R_ResetSunLightParseParams;
void * const imp_speex_default_user_handler = (void *)(uintptr_t)speex_default_user_handler;
void * const imp_CL_GetHudMsgIconMaterialName = (void *)(uintptr_t)CL_GetHudMsgIconMaterialName;
void * const imp_R_AddCmdDrawStretchPicRotate = (void *)(uintptr_t)R_AddCmdDrawStretchPicRotate;
void * const imp_R_Cmd_ReloadMaterialTextures = (void *)(uintptr_t)R_Cmd_ReloadMaterialTextures;
void * const imp_R_InterpretSunLightParseParams = (void *)(uintptr_t)R_InterpretSunLightParseParams;
void * const imp_Com_WriteLocalizedSoundAliasFiles = (void *)(uintptr_t)Com_WriteLocalizedSoundAliasFiles;
void * const imp_DObjBad = (void *)(uintptr_t)DObjBad;
void * const imp_FS_Read = (void *)(uintptr_t)FS_Read;
void * const imp_MT_Free = (void *)(uintptr_t)MT_Free;
void * const imp_Cmd_Argc = (void *)(uintptr_t)Cmd_Argc;
void * const imp_Cmd_Argv = (void *)(uintptr_t)Cmd_Argv;
void * const imp_FS_Write = (void *)(uintptr_t)FS_Write;
void * const imp_R_SetFog = (void *)(uintptr_t)R_SetFog;
void * const imp_CL_Ping_f = (void *)(uintptr_t)CL_Ping_f;
void * const imp_CL_Rcon_f = (void *)(uintptr_t)CL_Rcon_f;
void * const imp_FS_Path_f = (void *)(uintptr_t)FS_Path_f;
void * const imp_XModelBad = (void *)(uintptr_t)XModelBad;
void * const imp___ZN10CVAOPacket10sVAOStatusE = (void *)(uintptr_t)__ZN10CVAOPacket10sVAOStatusE;
void * const imp___ZN10CVAOPacket14sCurrentPacketE = (void *)(uintptr_t)__ZN10CVAOPacket14sCurrentPacketE;
void * const imp___ZN10CVAOPacket14sGenericPacketE = (void *)(uintptr_t)__ZN10CVAOPacket14sGenericPacketE;
void * const imp___ZN13COpenGLMatrix9sIdentityE = (void *)(uintptr_t)__ZN13COpenGLMatrix9sIdentityE;
void * const imp___ZN15CDirect3DDevice28mNeedsVertexShaderValidationE = (void *)(uintptr_t)__ZN15CDirect3DDevice28mNeedsVertexShaderValidationE;
void * const imp___ZN15CDirect3DDevice29mNeedsRasterizationValidationE = (void *)(uintptr_t)__ZN15CDirect3DDevice29mNeedsRasterizationValidationE;
void * const imp___ZN15CDirect3DDevice30mNeedsTransformationValidationE = (void *)(uintptr_t)__ZN15CDirect3DDevice30mNeedsTransformationValidationE;
void * const imp___ZN6CFence15sUnusedFenceIDsE = (void *)(uintptr_t)__ZN6CFence15sUnusedFenceIDsE;
void * const imp___ZN7COpenGL11sFrameCountE = (void *)(uintptr_t)__ZN7COpenGL11sFrameCountE;
void * const imp___ZN7COpenGL14sShowTextureIDE = (void *)(uintptr_t)__ZN7COpenGL14sShowTextureIDE;
void * const imp___ZN7COpenGL7sOpenGLE = (void *)(uintptr_t)__ZN7COpenGL7sOpenGLE;
void * const imp___ZN7COpenGL9sDrawFlagE = (void *)(uintptr_t)__ZN7COpenGL9sDrawFlagE;
void * const imp___ZTI14COpenGLTexture = (void *)(uintptr_t)__ZTI14COpenGLTexture;
void * const imp___ZTI17IDirect3DTexture9 = (void *)(uintptr_t)__ZTI17IDirect3DTexture9;
void * const imp___ZTV10COpenGLVAO = (void *)(uintptr_t)__ZTV10COpenGLVAO;
void * const imp___ZTV11CColorArray = (void *)(uintptr_t)__ZTV11CColorArray;
void * const imp___ZTV12CNormalArray = (void *)(uintptr_t)__ZTV12CNormalArray;
void * const imp___ZTV12CVertexArray = (void *)(uintptr_t)__ZTV12CVertexArray;
void * const imp___ZTV14COpenGLTexture = (void *)(uintptr_t)__ZTV14COpenGLTexture;
void * const imp___ZTV14CTexCoordArray = (void *)(uintptr_t)__ZTV14CTexCoordArray;
void * const imp___ZTV15CCacheInfoBlock = (void *)(uintptr_t)__ZTV15CCacheInfoBlock;
void * const imp___ZTV15CColorConverter = (void *)(uintptr_t)__ZTV15CColorConverter;
void * const imp___ZTV17IDirect3DTexture9 = (void *)(uintptr_t)__ZTV17IDirect3DTexture9;
void * const imp___ZTV18IDirect3DResource9 = (void *)(uintptr_t)__ZTV18IDirect3DResource9;
void * const imp___ZTV20CSecondaryColorArray = (void *)(uintptr_t)__ZTV20CSecondaryColorArray;
void * const imp___ZTV21IDirect3DBaseTexture9 = (void *)(uintptr_t)__ZTV21IDirect3DBaseTexture9;
void * const imp___ZTV21IDirect3DCubeTexture9 = (void *)(uintptr_t)__ZTV21IDirect3DCubeTexture9;
void * const imp___ZTV22CVAOPacketProgrammable = (void *)(uintptr_t)__ZTV22CVAOPacketProgrammable;
void * const imp___ZTV22IDirect3DVertexShader9 = (void *)(uintptr_t)__ZTV22IDirect3DVertexShader9;
void * const imp___ZTV23CVAOPacketFixedFunction = (void *)(uintptr_t)__ZTV23CVAOPacketFixedFunction;
void * const imp___ZTV23IDirect3DVolumeTexture9 = (void *)(uintptr_t)__ZTV23IDirect3DVolumeTexture9;
void * const imp___ZTV5Flash = (void *)(uintptr_t)__ZTV5Flash;
void * const imp___ZTV7CBaseVA = (void *)(uintptr_t)__ZTV7CBaseVA;
void * const imp___ZTV8IUnknown = (void *)(uintptr_t)__ZTV8IUnknown;
void * const imp_alwaysfails = (void *)(uintptr_t)alwaysfails;
void * const imp_backEnd = (void *)(uintptr_t)backEnd;
void * const imp_backEndData = (void *)(uintptr_t)backEndData;
void * const imp_bg_aimSpreadMoveSpeedThreshold = (void *)(uintptr_t)bg_aimSpreadMoveSpeedThreshold;
void * const imp_bg_bobAmplitudeDucked = (void *)(uintptr_t)bg_bobAmplitudeDucked;
void * const imp_bg_bobAmplitudeProne = (void *)(uintptr_t)bg_bobAmplitudeProne;
void * const imp_bg_bobAmplitudeStanding = (void *)(uintptr_t)bg_bobAmplitudeStanding;
void * const imp_bg_bobMax = (void *)(uintptr_t)bg_bobMax;
void * const imp_bg_fallDamageMaxHeight = (void *)(uintptr_t)bg_fallDamageMaxHeight;
void * const imp_bg_fallDamageMinHeight = (void *)(uintptr_t)bg_fallDamageMinHeight;
void * const imp_bg_foliagesnd_fastinterval = (void *)(uintptr_t)bg_foliagesnd_fastinterval;
void * const imp_bg_foliagesnd_maxspeed = (void *)(uintptr_t)bg_foliagesnd_maxspeed;
void * const imp_bg_foliagesnd_minspeed = (void *)(uintptr_t)bg_foliagesnd_minspeed;
void * const imp_bg_foliagesnd_resetinterval = (void *)(uintptr_t)bg_foliagesnd_resetinterval;
void * const imp_bg_foliagesnd_slowinterval = (void *)(uintptr_t)bg_foliagesnd_slowinterval;
void * const imp_bg_iNumWeapons = (void *)(uintptr_t)bg_iNumWeapons;
void * const imp_bg_itemlist = (void *)(uintptr_t)bg_itemlist;
void * const imp_bg_ladder_yawcap = (void *)(uintptr_t)bg_ladder_yawcap;
void * const imp_bg_numItems = (void *)(uintptr_t)bg_numItems;
void * const imp_bg_prone_yawcap = (void *)(uintptr_t)bg_prone_yawcap;
void * const imp_bg_swingSpeed = (void *)(uintptr_t)bg_swingSpeed;
void * const imp_bgs = (void *)(uintptr_t)bgs;
void * const imp_bulletPriorityMap = (void *)(uintptr_t)bulletPriorityMap;
void * const imp_cg = (void *)(uintptr_t)cg;
void * const imp_cgDC = (void *)(uintptr_t)cgDC;
void * const imp_cg_blood = (void *)(uintptr_t)cg_blood;
void * const imp_cg_brass = (void *)(uintptr_t)cg_brass;
void * const imp_cg_centerPrintY = (void *)(uintptr_t)cg_centerPrintY;
void * const imp_cg_centertime = (void *)(uintptr_t)cg_centertime;
void * const imp_cg_chatHeight = (void *)(uintptr_t)cg_chatHeight;
void * const imp_cg_chatTime = (void *)(uintptr_t)cg_chatTime;
void * const imp_cg_connectionIconSize = (void *)(uintptr_t)cg_connectionIconSize;
void * const imp_cg_constantSizeHeadIcons = (void *)(uintptr_t)cg_constantSizeHeadIcons;
void * const imp_cg_crosshairAlpha = (void *)(uintptr_t)cg_crosshairAlpha;
void * const imp_cg_crosshairAlphaMin = (void *)(uintptr_t)cg_crosshairAlphaMin;
void * const imp_cg_crosshairDynamic = (void *)(uintptr_t)cg_crosshairDynamic;
void * const imp_cg_crosshairEnemyColor = (void *)(uintptr_t)cg_crosshairEnemyColor;
void * const imp_cg_cursorHints = (void *)(uintptr_t)cg_cursorHints;
void * const imp_cg_debugEvents = (void *)(uintptr_t)cg_debugEvents;
void * const imp_cg_debugPosition = (void *)(uintptr_t)cg_debugPosition;
void * const imp_cg_descriptiveText = (void *)(uintptr_t)cg_descriptiveText;
void * const imp_cg_draw2D = (void *)(uintptr_t)cg_draw2D;
void * const imp_cg_drawBreathHint = (void *)(uintptr_t)cg_drawBreathHint;
void * const imp_cg_drawCrosshair = (void *)(uintptr_t)cg_drawCrosshair;
void * const imp_cg_drawCrosshairNames = (void *)(uintptr_t)cg_drawCrosshairNames;
void * const imp_cg_drawCrosshairNamesPosX = (void *)(uintptr_t)cg_drawCrosshairNamesPosX;
void * const imp_cg_drawCrosshairNamesPosY = (void *)(uintptr_t)cg_drawCrosshairNamesPosY;
void * const imp_cg_drawFPS = (void *)(uintptr_t)cg_drawFPS;
void * const imp_cg_drawGameMessages = (void *)(uintptr_t)cg_drawGameMessages;
void * const imp_cg_drawGun = (void *)(uintptr_t)cg_drawGun;
void * const imp_cg_drawHealth = (void *)(uintptr_t)cg_drawHealth;
void * const imp_cg_drawLagometer = (void *)(uintptr_t)cg_drawLagometer;
void * const imp_cg_drawMantleHint = (void *)(uintptr_t)cg_drawMantleHint;
void * const imp_cg_drawMaterial = (void *)(uintptr_t)cg_drawMaterial;
void * const imp_cg_drawScriptUsage = (void *)(uintptr_t)cg_drawScriptUsage;
void * const imp_cg_drawSnapshot = (void *)(uintptr_t)cg_drawSnapshot;
void * const imp_cg_drawSoundOverlay = (void *)(uintptr_t)cg_drawSoundOverlay;
void * const imp_cg_drawTurretCrosshair = (void *)(uintptr_t)cg_drawTurretCrosshair;
void * const imp_cg_dumpAnims = (void *)(uintptr_t)cg_dumpAnims;
void * const imp_cg_entities = (void *)(uintptr_t)cg_entities;
void * const imp_cg_errorDecay = (void *)(uintptr_t)cg_errorDecay;
void * const imp_cg_footsteps = (void *)(uintptr_t)cg_footsteps;
void * const imp_cg_fov = (void *)(uintptr_t)cg_fov;
void * const imp_cg_fovMin = (void *)(uintptr_t)cg_fovMin;
void * const imp_cg_fovScale = (void *)(uintptr_t)cg_fovScale;
void * const imp_cg_gun_move_f = (void *)(uintptr_t)cg_gun_move_f;
void * const imp_cg_gun_move_minspeed = (void *)(uintptr_t)cg_gun_move_minspeed;
void * const imp_cg_gun_move_r = (void *)(uintptr_t)cg_gun_move_r;
void * const imp_cg_gun_move_rate = (void *)(uintptr_t)cg_gun_move_rate;
void * const imp_cg_gun_move_u = (void *)(uintptr_t)cg_gun_move_u;
void * const imp_cg_gun_ofs_f = (void *)(uintptr_t)cg_gun_ofs_f;
void * const imp_cg_gun_ofs_r = (void *)(uintptr_t)cg_gun_ofs_r;
void * const imp_cg_gun_ofs_u = (void *)(uintptr_t)cg_gun_ofs_u;
void * const imp_cg_gun_x = (void *)(uintptr_t)cg_gun_x;
void * const imp_cg_gun_y = (void *)(uintptr_t)cg_gun_y;
void * const imp_cg_gun_z = (void *)(uintptr_t)cg_gun_z;
void * const imp_cg_headIconMinScreenRadius = (void *)(uintptr_t)cg_headIconMinScreenRadius;
void * const imp_cg_hintFadeTime = (void *)(uintptr_t)cg_hintFadeTime;
void * const imp_cg_hudChatPosition = (void *)(uintptr_t)cg_hudChatPosition;
void * const imp_cg_hudCompassMaxRange = (void *)(uintptr_t)cg_hudCompassMaxRange;
void * const imp_cg_hudCompassMinRadius = (void *)(uintptr_t)cg_hudCompassMinRadius;
void * const imp_cg_hudCompassMinRange = (void *)(uintptr_t)cg_hudCompassMinRange;
void * const imp_cg_hudCompassSize = (void *)(uintptr_t)cg_hudCompassSize;
void * const imp_cg_hudCompassSoundPingFadeTime = (void *)(uintptr_t)cg_hudCompassSoundPingFadeTime;
void * const imp_cg_hudCompassSpringyPointers = (void *)(uintptr_t)cg_hudCompassSpringyPointers;
void * const imp_cg_hudDamageIconHeight = (void *)(uintptr_t)cg_hudDamageIconHeight;
void * const imp_cg_hudDamageIconInScope = (void *)(uintptr_t)cg_hudDamageIconInScope;
void * const imp_cg_hudDamageIconOffset = (void *)(uintptr_t)cg_hudDamageIconOffset;
void * const imp_cg_hudDamageIconTime = (void *)(uintptr_t)cg_hudDamageIconTime;
void * const imp_cg_hudDamageIconWidth = (void *)(uintptr_t)cg_hudDamageIconWidth;
void * const imp_cg_hudGrenadeIconHeight = (void *)(uintptr_t)cg_hudGrenadeIconHeight;
void * const imp_cg_hudGrenadeIconInScope = (void *)(uintptr_t)cg_hudGrenadeIconInScope;
void * const imp_cg_hudGrenadeIconMaxHeight = (void *)(uintptr_t)cg_hudGrenadeIconMaxHeight;
void * const imp_cg_hudGrenadeIconMaxRange = (void *)(uintptr_t)cg_hudGrenadeIconMaxRange;
void * const imp_cg_hudGrenadeIconOffset = (void *)(uintptr_t)cg_hudGrenadeIconOffset;
void * const imp_cg_hudGrenadeIconWidth = (void *)(uintptr_t)cg_hudGrenadeIconWidth;
void * const imp_cg_hudGrenadePointerHeight = (void *)(uintptr_t)cg_hudGrenadePointerHeight;
void * const imp_cg_hudGrenadePointerPivot = (void *)(uintptr_t)cg_hudGrenadePointerPivot;
void * const imp_cg_hudGrenadePointerPulseFreq = (void *)(uintptr_t)cg_hudGrenadePointerPulseFreq;
void * const imp_cg_hudGrenadePointerPulseMax = (void *)(uintptr_t)cg_hudGrenadePointerPulseMax;
void * const imp_cg_hudGrenadePointerPulseMin = (void *)(uintptr_t)cg_hudGrenadePointerPulseMin;
void * const imp_cg_hudGrenadePointerWidth = (void *)(uintptr_t)cg_hudGrenadePointerWidth;
void * const imp_cg_hudObjectiveMaxRange = (void *)(uintptr_t)cg_hudObjectiveMaxRange;
void * const imp_cg_hudObjectiveMinAlpha = (void *)(uintptr_t)cg_hudObjectiveMinAlpha;
void * const imp_cg_hudProneY = (void *)(uintptr_t)cg_hudProneY;
void * const imp_cg_hudSayPosition = (void *)(uintptr_t)cg_hudSayPosition;
void * const imp_cg_hudStanceFlash = (void *)(uintptr_t)cg_hudStanceFlash;
void * const imp_cg_hudStanceHintPrints = (void *)(uintptr_t)cg_hudStanceHintPrints;
void * const imp_cg_items = (void *)(uintptr_t)cg_items;
void * const imp_cg_marks = (void *)(uintptr_t)cg_marks;
void * const imp_cg_marksLimit = (void *)(uintptr_t)cg_marksLimit;
void * const imp_cg_minicon = (void *)(uintptr_t)cg_minicon;
void * const imp_cg_nopredict = (void *)(uintptr_t)cg_nopredict;
void * const imp_cg_paused = (void *)(uintptr_t)cg_paused;
void * const imp_cg_predictItems = (void *)(uintptr_t)cg_predictItems;
void * const imp_cg_scoreboardBannerHeight = (void *)(uintptr_t)cg_scoreboardBannerHeight;
void * const imp_cg_scoreboardScrollStep = (void *)(uintptr_t)cg_scoreboardScrollStep;
void * const imp_cg_scriptIconSize = (void *)(uintptr_t)cg_scriptIconSize;
void * const imp_cg_shock_mouse = (void *)(uintptr_t)cg_shock_mouse;
void * const imp_cg_shock_mouse_fadeTime = (void *)(uintptr_t)cg_shock_mouse_fadeTime;
void * const imp_cg_shock_mouse_maxpitchspeed = (void *)(uintptr_t)cg_shock_mouse_maxpitchspeed;
void * const imp_cg_shock_mouse_maxyawspeed = (void *)(uintptr_t)cg_shock_mouse_maxyawspeed;
void * const imp_cg_shock_mouse_sensitivityscale = (void *)(uintptr_t)cg_shock_mouse_sensitivityscale;
void * const imp_cg_shock_screenBlendFadeTime = (void *)(uintptr_t)cg_shock_screenBlendFadeTime;
void * const imp_cg_shock_screenBlendTime = (void *)(uintptr_t)cg_shock_screenBlendTime;
void * const imp_cg_shock_sound = (void *)(uintptr_t)cg_shock_sound;
void * const imp_cg_shock_soundDryLevel = (void *)(uintptr_t)cg_shock_soundDryLevel;
void * const imp_cg_shock_soundFadeInTime = (void *)(uintptr_t)cg_shock_soundFadeInTime;
void * const imp_cg_shock_soundFadeOutTime = (void *)(uintptr_t)cg_shock_soundFadeOutTime;
void * const imp_cg_shock_soundLoopEndDelay = (void *)(uintptr_t)cg_shock_soundLoopEndDelay;
void * const imp_cg_shock_soundLoopFadeTime = (void *)(uintptr_t)cg_shock_soundLoopFadeTime;
void * const imp_cg_shock_soundModEndDelay = (void *)(uintptr_t)cg_shock_soundModEndDelay;
void * const imp_cg_shock_soundRoomType = (void *)(uintptr_t)cg_shock_soundRoomType;
void * const imp_cg_shock_soundWetLevel = (void *)(uintptr_t)cg_shock_soundWetLevel;
void * const imp_cg_shock_viewKickPeriod = (void *)(uintptr_t)cg_shock_viewKickPeriod;
void * const imp_cg_shock_viewKickRadius = (void *)(uintptr_t)cg_shock_viewKickRadius;
void * const imp_cg_shock_volume_announcer = (void *)(uintptr_t)cg_shock_volume_announcer;
void * const imp_cg_shock_volume_auto = (void *)(uintptr_t)cg_shock_volume_auto;
void * const imp_cg_shock_volume_auto2d = (void *)(uintptr_t)cg_shock_volume_auto2d;
void * const imp_cg_shock_volume_body = (void *)(uintptr_t)cg_shock_volume_body;
void * const imp_cg_shock_volume_item = (void *)(uintptr_t)cg_shock_volume_item;
void * const imp_cg_shock_volume_local = (void *)(uintptr_t)cg_shock_volume_local;
void * const imp_cg_shock_volume_menu = (void *)(uintptr_t)cg_shock_volume_menu;
void * const imp_cg_shock_volume_music = (void *)(uintptr_t)cg_shock_volume_music;
void * const imp_cg_shock_volume_shellshock = (void *)(uintptr_t)cg_shock_volume_shellshock;
void * const imp_cg_shock_volume_voice = (void *)(uintptr_t)cg_shock_volume_voice;
void * const imp_cg_shock_volume_weapon = (void *)(uintptr_t)cg_shock_volume_weapon;
void * const imp_cg_showmiss = (void *)(uintptr_t)cg_showmiss;
void * const imp_cg_subtitleCharHeight = (void *)(uintptr_t)cg_subtitleCharHeight;
void * const imp_cg_subtitlePosX = (void *)(uintptr_t)cg_subtitlePosX;
void * const imp_cg_subtitlePosY = (void *)(uintptr_t)cg_subtitlePosY;
void * const imp_cg_subtitles = (void *)(uintptr_t)cg_subtitles;
void * const imp_cg_synchronousClients = (void *)(uintptr_t)cg_synchronousClients;
void * const imp_cg_teamChatsOnly = (void *)(uintptr_t)cg_teamChatsOnly;
void * const imp_cg_thirdPerson = (void *)(uintptr_t)cg_thirdPerson;
void * const imp_cg_thirdPersonAngle = (void *)(uintptr_t)cg_thirdPersonAngle;
void * const imp_cg_thirdPersonRange = (void *)(uintptr_t)cg_thirdPersonRange;
void * const imp_cg_tracerChance = (void *)(uintptr_t)cg_tracerChance;
void * const imp_cg_tracerLength = (void *)(uintptr_t)cg_tracerLength;
void * const imp_cg_tracerScale = (void *)(uintptr_t)cg_tracerScale;
void * const imp_cg_tracerScaleDistRange = (void *)(uintptr_t)cg_tracerScaleDistRange;
void * const imp_cg_tracerScaleMinDist = (void *)(uintptr_t)cg_tracerScaleMinDist;
void * const imp_cg_tracerSpeed = (void *)(uintptr_t)cg_tracerSpeed;
void * const imp_cg_tracerWidth = (void *)(uintptr_t)cg_tracerWidth;
void * const imp_cg_viewsize = (void *)(uintptr_t)cg_viewsize;
void * const imp_cg_voiceIconSize = (void *)(uintptr_t)cg_voiceIconSize;
void * const imp_cg_weaponCycleDelay = (void *)(uintptr_t)cg_weaponCycleDelay;
void * const imp_cg_weapons = (void *)(uintptr_t)cg_weapons;
void * const imp_cg_youInKillCamSize = (void *)(uintptr_t)cg_youInKillCamSize;
void * const imp_cgs = (void *)(uintptr_t)cgs;
void * const imp_chatField = (void *)(uintptr_t)chatField;
void * const imp_chat_team = (void *)(uintptr_t)chat_team;
void * const imp_cl = (void *)(uintptr_t)cl;
void * const imp_cl_activeAction = (void *)(uintptr_t)cl_activeAction;
void * const imp_cl_anglespeedkey = (void *)(uintptr_t)cl_anglespeedkey;
void * const imp_cl_bypassMouseInput = (void *)(uintptr_t)cl_bypassMouseInput;
void * const imp_cl_cdkey = (void *)(uintptr_t)cl_cdkey;
void * const imp_cl_cdkeychecksum = (void *)(uintptr_t)cl_cdkeychecksum;
void * const imp_cl_connectedToPureServer = (void *)(uintptr_t)cl_connectedToPureServer;
void * const imp_cl_freelook = (void *)(uintptr_t)cl_freelook;
void * const imp_cl_freezeDemo = (void *)(uintptr_t)cl_freezeDemo;
void * const imp_cl_inGameVideo = (void *)(uintptr_t)cl_inGameVideo;
void * const imp_cl_maxpackets = (void *)(uintptr_t)cl_maxpackets;
void * const imp_cl_mouseAccel = (void *)(uintptr_t)cl_mouseAccel;
void * const imp_cl_nodelta = (void *)(uintptr_t)cl_nodelta;
void * const imp_cl_noprint = (void *)(uintptr_t)cl_noprint;
void * const imp_cl_packetdup = (void *)(uintptr_t)cl_packetdup;
void * const imp_cl_paused = (void *)(uintptr_t)cl_paused;
void * const imp_cl_pinglist = (void *)(uintptr_t)cl_pinglist;
void * const imp_cl_pitchspeed = (void *)(uintptr_t)cl_pitchspeed;
void * const imp_cl_sensitivity = (void *)(uintptr_t)cl_sensitivity;
void * const imp_cl_serverStatusResendTime = (void *)(uintptr_t)cl_serverStatusResendTime;
void * const imp_cl_showMouseRate = (void *)(uintptr_t)cl_showMouseRate;
void * const imp_cl_showSend = (void *)(uintptr_t)cl_showSend;
void * const imp_cl_showServerCommands = (void *)(uintptr_t)cl_showServerCommands;
void * const imp_cl_showTimeDelta = (void *)(uintptr_t)cl_showTimeDelta;
void * const imp_cl_shownet = (void *)(uintptr_t)cl_shownet;
void * const imp_cl_shownuments = (void *)(uintptr_t)cl_shownuments;
void * const imp_cl_talking = (void *)(uintptr_t)cl_talking;
void * const imp_cl_voice = (void *)(uintptr_t)cl_voice;
void * const imp_cl_yawspeed = (void *)(uintptr_t)cl_yawspeed;
void * const imp_clc = (void *)(uintptr_t)clc;
void * const imp_clients = (void *)(uintptr_t)clients;
void * const imp_cls = (void *)(uintptr_t)cls;
void * const imp_cm = (void *)(uintptr_t)cm;
void * const imp_colorBlack = (void *)(uintptr_t)colorBlack;
void * const imp_colorBlue = (void *)(uintptr_t)colorBlue;
void * const imp_colorCyan = (void *)(uintptr_t)colorCyan;
void * const imp_colorGreen = (void *)(uintptr_t)colorGreen;
void * const imp_colorLtCyan = (void *)(uintptr_t)colorLtCyan;
void * const imp_colorLtGrey = (void *)(uintptr_t)colorLtGrey;
void * const imp_colorLtYellow = (void *)(uintptr_t)colorLtYellow;
void * const imp_colorMagenta = (void *)(uintptr_t)colorMagenta;
void * const imp_colorMdCyan = (void *)(uintptr_t)colorMdCyan;
void * const imp_colorRed = (void *)(uintptr_t)colorRed;
void * const imp_colorWhite = (void *)(uintptr_t)colorWhite;
void * const imp_colorYellow = (void *)(uintptr_t)colorYellow;
void * const imp_com_dedicated = (void *)(uintptr_t)com_dedicated;
void * const imp_com_developer = (void *)(uintptr_t)com_developer;
void * const imp_com_errorEntered = (void *)(uintptr_t)com_errorEntered;
void * const imp_com_expectedHunkUsage = (void *)(uintptr_t)com_expectedHunkUsage;
void * const imp_com_fileAccessed = (void *)(uintptr_t)com_fileAccessed;
void * const imp_com_fixedConsolePosition = (void *)(uintptr_t)com_fixedConsolePosition;
void * const imp_com_frameTime = (void *)(uintptr_t)com_frameTime;
void * const imp_com_logfile = (void *)(uintptr_t)com_logfile;
void * const imp_com_playerProfile = (void *)(uintptr_t)com_playerProfile;
void * const imp_com_statmon = (void *)(uintptr_t)com_statmon;
void * const imp_com_sv_running = (void *)(uintptr_t)com_sv_running;
void * const imp_com_timescaleValue = (void *)(uintptr_t)com_timescaleValue;
void * const imp_com_viewlog = (void *)(uintptr_t)com_viewlog;
void * const imp_current_audioCallback = (void *)(uintptr_t)current_audioCallback;
void * const imp_developer = (void *)(uintptr_t)developer;
void * const imp_dvarCount = (void *)(uintptr_t)dvarCount;
void * const imp_dvar_modifiedFlags = (void *)(uintptr_t)dvar_modifiedFlags;
void * const imp_dx = (void *)(uintptr_t)dx;
void * const imp_dxState = (void *)(uintptr_t)dxState;
void * const imp_effectActiveCountBolt = (void *)(uintptr_t)effectActiveCountBolt;
void * const imp_effectActiveCountNonBolt = (void *)(uintptr_t)effectActiveCountNonBolt;
void * const imp_entityHandlers = (void *)(uintptr_t)entityHandlers;
void * const imp_eventnames = (void *)(uintptr_t)eventnames;
void * const imp_frame_msec = (void *)(uintptr_t)frame_msec;
void * const imp_friction = (void *)(uintptr_t)friction;
void * const imp_frontEndDataOut = (void *)(uintptr_t)frontEndDataOut;
void * const imp_fs_basepath = (void *)(uintptr_t)fs_basepath;
void * const imp_fs_cdpath = (void *)(uintptr_t)fs_cdpath;
void * const imp_fs_checksumFeed = (void *)(uintptr_t)fs_checksumFeed;
void * const imp_fs_copyfiles = (void *)(uintptr_t)fs_copyfiles;
void * const imp_fs_debug = (void *)(uintptr_t)fs_debug;
void * const imp_fs_fakeChkSum = (void *)(uintptr_t)fs_fakeChkSum;
void * const imp_fs_gamedir = (void *)(uintptr_t)fs_gamedir;
void * const imp_fs_homepath = (void *)(uintptr_t)fs_homepath;
void * const imp_fs_ignoreLocalized = (void *)(uintptr_t)fs_ignoreLocalized;
void * const imp_fs_numServerIwds = (void *)(uintptr_t)fs_numServerIwds;
void * const imp_fs_numServerReferencedIwds = (void *)(uintptr_t)fs_numServerReferencedIwds;
void * const imp_fs_restrict = (void *)(uintptr_t)fs_restrict;
void * const imp_fs_searchpaths = (void *)(uintptr_t)fs_searchpaths;
void * const imp_fs_serverIwdNames = (void *)(uintptr_t)fs_serverIwdNames;
void * const imp_fs_serverIwds = (void *)(uintptr_t)fs_serverIwds;
void * const imp_fs_serverReferencedIwdNames = (void *)(uintptr_t)fs_serverReferencedIwdNames;
void * const imp_fs_serverReferencedIwds = (void *)(uintptr_t)fs_serverReferencedIwds;
void * const imp_fsh = (void *)(uintptr_t)fsh;
void * const imp_fxSchedulers = (void *)(uintptr_t)fxSchedulers;
void * const imp_fx_camera_valid = (void *)(uintptr_t)fx_camera_valid;
void * const imp_fx_count = (void *)(uintptr_t)fx_count;
void * const imp_fx_cull = (void *)(uintptr_t)fx_cull;
void * const imp_fx_debug = (void *)(uintptr_t)fx_debug;
void * const imp_fx_debugBolt = (void *)(uintptr_t)fx_debugBolt;
void * const imp_fx_draw = (void *)(uintptr_t)fx_draw;
void * const imp_fx_enable = (void *)(uintptr_t)fx_enable;
void * const imp_fx_freeze = (void *)(uintptr_t)fx_freeze;
void * const imp_fx_sort = (void *)(uintptr_t)fx_sort;
void * const imp_fx_visMinTraceDist = (void *)(uintptr_t)fx_visMinTraceDist;
void * const imp_gConsoleRunning = (void *)(uintptr_t)gConsoleRunning;
void * const imp_g_CurrentGenericPacket = (void *)(uintptr_t)g_CurrentGenericPacket;
void * const imp_g_EndPos = (void *)(uintptr_t)g_EndPos;
void * const imp_g_InhibitCopy = (void *)(uintptr_t)g_InhibitCopy;
void * const imp_g_InhibitOpenGLErrors = (void *)(uintptr_t)g_InhibitOpenGLErrors;
void * const imp_g_NoScriptSpam = (void *)(uintptr_t)g_NoScriptSpam;
void * const imp_g_NoTextureID = (void *)(uintptr_t)g_NoTextureID;
void * const imp_g_RenderToShadowCookie = (void *)(uintptr_t)g_RenderToShadowCookie;
void * const imp_g_TotalFilterPasses = (void *)(uintptr_t)g_TotalFilterPasses;
void * const imp_g_VAOID = (void *)(uintptr_t)g_VAOID;
void * const imp_g_WarmOff = (void *)(uintptr_t)g_WarmOff;
void * const imp_g_allowVote = (void *)(uintptr_t)g_allowVote;
void * const imp_g_antilag = (void *)(uintptr_t)g_antilag;
void * const imp_g_banIPs = (void *)(uintptr_t)g_banIPs;
void * const imp_g_cheats = (void *)(uintptr_t)g_cheats;
void * const imp_g_clonePlayerMaxVelocity = (void *)(uintptr_t)g_clonePlayerMaxVelocity;
void * const imp_g_consoleField = (void *)(uintptr_t)g_consoleField;
void * const imp_g_console_char_height = (void *)(uintptr_t)g_console_char_height;
void * const imp_g_console_field_width = (void *)(uintptr_t)g_console_field_width;
void * const imp_g_current_bandwidth_setting = (void *)(uintptr_t)g_current_bandwidth_setting;
void * const imp_g_deadChat = (void *)(uintptr_t)g_deadChat;
void * const imp_g_debugDamage = (void *)(uintptr_t)g_debugDamage;
void * const imp_g_debugLocDamage = (void *)(uintptr_t)g_debugLocDamage;
void * const imp_g_dedicated = (void *)(uintptr_t)g_dedicated;
void * const imp_g_disableRendering = (void *)(uintptr_t)g_disableRendering;
void * const imp_g_dropForwardSpeed = (void *)(uintptr_t)g_dropForwardSpeed;
void * const imp_g_dropUpSpeedBase = (void *)(uintptr_t)g_dropUpSpeedBase;
void * const imp_g_dropUpSpeedRand = (void *)(uintptr_t)g_dropUpSpeedRand;
void * const imp_g_editingField = (void *)(uintptr_t)g_editingField;
void * const imp_g_effectVisArray = (void *)(uintptr_t)g_effectVisArray;
void * const imp_g_effectVisArrayCount = (void *)(uintptr_t)g_effectVisArrayCount;
void * const imp_g_encoder_samplerate = (void *)(uintptr_t)g_encoder_samplerate;
void * const imp_g_entities = (void *)(uintptr_t)g_entities;
void * const imp_g_frame_size = (void *)(uintptr_t)g_frame_size;
void * const imp_g_friendlyNameDist = (void *)(uintptr_t)g_friendlyNameDist;
void * const imp_g_friendlyfireDist = (void *)(uintptr_t)g_friendlyfireDist;
void * const imp_g_gametype = (void *)(uintptr_t)g_gametype;
void * const imp_g_gravity = (void *)(uintptr_t)g_gravity;
void * const imp_g_hudelems = (void *)(uintptr_t)g_hudelems;
void * const imp_g_inactivity = (void *)(uintptr_t)g_inactivity;
void * const imp_g_knockback = (void *)(uintptr_t)g_knockback;
void * const imp_g_mantleBlockTimeBuffer = (void *)(uintptr_t)g_mantleBlockTimeBuffer;
void * const imp_g_maxDroppedWeapons = (void *)(uintptr_t)g_maxDroppedWeapons;
void * const imp_g_maxclients = (void *)(uintptr_t)g_maxclients;
void * const imp_g_motd = (void *)(uintptr_t)g_motd;
void * const imp_g_oldVoting = (void *)(uintptr_t)g_oldVoting;
void * const imp_g_password = (void *)(uintptr_t)g_password;
void * const imp_g_playerCollisionEjectSpeed = (void *)(uintptr_t)g_playerCollisionEjectSpeed;
void * const imp_g_qport = (void *)(uintptr_t)g_qport;
void * const imp_g_rendererExists = (void *)(uintptr_t)g_rendererExists;
void * const imp_g_scr_data = (void *)(uintptr_t)g_scr_data;
void * const imp_g_skinBuffers = (void *)(uintptr_t)g_skinBuffers;
void * const imp_g_smoothClients = (void *)(uintptr_t)g_smoothClients;
void * const imp_g_snd = (void *)(uintptr_t)g_snd;
void * const imp_g_special = (void *)(uintptr_t)g_special;
void * const imp_g_speed = (void *)(uintptr_t)g_speed;
void * const imp_g_synchronousClients = (void *)(uintptr_t)g_synchronousClients;
void * const imp_g_traceThreadInfo = (void *)(uintptr_t)g_traceThreadInfo;
void * const imp_g_useholdspawndelay = (void *)(uintptr_t)g_useholdspawndelay;
void * const imp_g_useholdtime = (void *)(uintptr_t)g_useholdtime;
void * const imp_g_voiceChatTalkingDuration = (void *)(uintptr_t)g_voiceChatTalkingDuration;
void * const imp_g_waitingForServer = (void *)(uintptr_t)g_waitingForServer;
void * const imp_g_weaponAmmoPools = (void *)(uintptr_t)g_weaponAmmoPools;
void * const imp_g_wv = (void *)(uintptr_t)g_wv;
void * const imp_gameInitialized = (void *)(uintptr_t)gameInitialized;
void * const imp_hintStrings = (void *)(uintptr_t)hintStrings;
void * const imp_historyEditLines = (void *)(uintptr_t)historyEditLines;
void * const imp_hud_fade_ammodisplay = (void *)(uintptr_t)hud_fade_ammodisplay;
void * const imp_hud_fade_compass = (void *)(uintptr_t)hud_fade_compass;
void * const imp_hud_fade_healthbar = (void *)(uintptr_t)hud_fade_healthbar;
void * const imp_hud_fade_offhand = (void *)(uintptr_t)hud_fade_offhand;
void * const imp_hud_fade_stance = (void *)(uintptr_t)hud_fade_stance;
void * const imp_hud_health_startpulse_injured = (void *)(uintptr_t)hud_health_startpulse_injured;
void * const imp_inertiaAngle = (void *)(uintptr_t)inertiaAngle;
void * const imp_inertiaDebug = (void *)(uintptr_t)inertiaDebug;
void * const imp_inertiaMax = (void *)(uintptr_t)inertiaMax;
void * const imp_infoParms = (void *)(uintptr_t)infoParms;
void * const imp_keys = (void *)(uintptr_t)keys;
void * const imp_legacyHacks = (void *)(uintptr_t)legacyHacks;
void * const imp_legacyHacksArray = (void *)(uintptr_t)legacyHacksArray;
void * const imp_level = (void *)(uintptr_t)level;
void * const imp_level_bgs = (void *)(uintptr_t)level_bgs;
void * const imp_loc_language = (void *)(uintptr_t)loc_language;
void * const imp_loc_warnings = (void *)(uintptr_t)loc_warnings;
void * const imp_loc_warningsAsErrors = (void *)(uintptr_t)loc_warningsAsErrors;
void * const imp_m_filter = (void *)(uintptr_t)m_filter;
void * const imp_m_forward = (void *)(uintptr_t)m_forward;
void * const imp_m_pitch = (void *)(uintptr_t)m_pitch;
void * const imp_m_side = (void *)(uintptr_t)m_side;
void * const imp_m_yaw = (void *)(uintptr_t)m_yaw;
void * const imp_modNames = (void *)(uintptr_t)modNames;
void * const imp_net_lanauthorize = (void *)(uintptr_t)net_lanauthorize;
void * const imp_net_profile = (void *)(uintptr_t)net_profile;
void * const imp_net_showprofile = (void *)(uintptr_t)net_showprofile;
void * const imp_nextdemo = (void *)(uintptr_t)nextdemo;
void * const imp_nextmap = (void *)(uintptr_t)nextmap;
void * const imp_playerMaxs = (void *)(uintptr_t)playerMaxs;
void * const imp_playerMins = (void *)(uintptr_t)playerMins;
void * const imp_player_adsExitDelay = (void *)(uintptr_t)player_adsExitDelay;
void * const imp_player_backSpeedScale = (void *)(uintptr_t)player_backSpeedScale;
void * const imp_player_breath_fire_delay = (void *)(uintptr_t)player_breath_fire_delay;
void * const imp_player_breath_gasp_lerp = (void *)(uintptr_t)player_breath_gasp_lerp;
void * const imp_player_breath_gasp_scale = (void *)(uintptr_t)player_breath_gasp_scale;
void * const imp_player_breath_gasp_time = (void *)(uintptr_t)player_breath_gasp_time;
void * const imp_player_breath_hold_lerp = (void *)(uintptr_t)player_breath_hold_lerp;
void * const imp_player_breath_hold_time = (void *)(uintptr_t)player_breath_hold_time;
void * const imp_player_breath_snd_delay = (void *)(uintptr_t)player_breath_snd_delay;
void * const imp_player_breath_snd_lerp = (void *)(uintptr_t)player_breath_snd_lerp;
void * const imp_player_dmgtimer_maxTime = (void *)(uintptr_t)player_dmgtimer_maxTime;
void * const imp_player_dmgtimer_minScale = (void *)(uintptr_t)player_dmgtimer_minScale;
void * const imp_player_dmgtimer_stumbleTime = (void *)(uintptr_t)player_dmgtimer_stumbleTime;
void * const imp_player_dmgtimer_timePerPoint = (void *)(uintptr_t)player_dmgtimer_timePerPoint;
void * const imp_player_footstepsThreshhold = (void *)(uintptr_t)player_footstepsThreshhold;
void * const imp_player_meleeHeight = (void *)(uintptr_t)player_meleeHeight;
void * const imp_player_meleeRange = (void *)(uintptr_t)player_meleeRange;
void * const imp_player_meleeWidth = (void *)(uintptr_t)player_meleeWidth;
void * const imp_player_moveThreshhold = (void *)(uintptr_t)player_moveThreshhold;
void * const imp_player_scopeExitOnDamage = (void *)(uintptr_t)player_scopeExitOnDamage;
void * const imp_player_spectateSpeedScale = (void *)(uintptr_t)player_spectateSpeedScale;
void * const imp_player_strafeSpeedScale = (void *)(uintptr_t)player_strafeSpeedScale;
void * const imp_player_toggleBinoculars = (void *)(uintptr_t)player_toggleBinoculars;
void * const imp_player_turnAnims = (void *)(uintptr_t)player_turnAnims;
void * const imp_player_view_pitch_down = (void *)(uintptr_t)player_view_pitch_down;
void * const imp_player_view_pitch_up = (void *)(uintptr_t)player_view_pitch_up;
void * const imp_pmoveHandlers = (void *)(uintptr_t)pmoveHandlers;
void * const imp_privateEffectActiveCountBolt = (void *)(uintptr_t)privateEffectActiveCountBolt;
void * const imp_privateEffectActiveCountNonBolt = (void *)(uintptr_t)privateEffectActiveCountNonBolt;
void * const imp_r_aaAlpha = (void *)(uintptr_t)r_aaAlpha;
void * const imp_r_aaSamples = (void *)(uintptr_t)r_aaSamples;
void * const imp_r_anisotropy = (void *)(uintptr_t)r_anisotropy;
void * const imp_r_aspectRatio = (void *)(uintptr_t)r_aspectRatio;
void * const imp_r_blur = (void *)(uintptr_t)r_blur;
void * const imp_r_clearColor = (void *)(uintptr_t)r_clearColor;
void * const imp_r_colorMap = (void *)(uintptr_t)r_colorMap;
void * const imp_r_cosinePowerMapShift = (void *)(uintptr_t)r_cosinePowerMapShift;
void * const imp_r_debugEntCounts = (void *)(uintptr_t)r_debugEntCounts;
void * const imp_r_debugShader = (void *)(uintptr_t)r_debugShader;
void * const imp_r_depthPrepassModels = (void *)(uintptr_t)r_depthPrepassModels;
void * const imp_r_displayRefresh = (void *)(uintptr_t)r_displayRefresh;
void * const imp_r_distortion = (void *)(uintptr_t)r_distortion;
void * const imp_r_dlightLimit = (void *)(uintptr_t)r_dlightLimit;
void * const imp_r_drawBModels = (void *)(uintptr_t)r_drawBModels;
void * const imp_r_drawDecals = (void *)(uintptr_t)r_drawDecals;
void * const imp_r_drawEntities = (void *)(uintptr_t)r_drawEntities;
void * const imp_r_drawPrimCap = (void *)(uintptr_t)r_drawPrimCap;
void * const imp_r_drawPrimFloor = (void *)(uintptr_t)r_drawPrimFloor;
void * const imp_r_drawSModels = (void *)(uintptr_t)r_drawSModels;
void * const imp_r_drawSun = (void *)(uintptr_t)r_drawSun;
void * const imp_r_drawWater = (void *)(uintptr_t)r_drawWater;
void * const imp_r_drawWorld = (void *)(uintptr_t)r_drawWorld;
void * const imp_r_drawXModels = (void *)(uintptr_t)r_drawXModels;
void * const imp_r_fog = (void *)(uintptr_t)r_fog;
void * const imp_r_forceLod = (void *)(uintptr_t)r_forceLod;
void * const imp_r_fullbright = (void *)(uintptr_t)r_fullbright;
void * const imp_r_gamma = (void *)(uintptr_t)r_gamma;
void * const imp_r_glow = (void *)(uintptr_t)r_glow;
void * const imp_r_glowBloomCutoff = (void *)(uintptr_t)r_glowBloomCutoff;
void * const imp_r_glowBloomDesaturation = (void *)(uintptr_t)r_glowBloomDesaturation;
void * const imp_r_glowBloomIntensity = (void *)(uintptr_t)r_glowBloomIntensity;
void * const imp_r_glowRadius = (void *)(uintptr_t)r_glowRadius;
void * const imp_r_glowSkyBleedIntensity = (void *)(uintptr_t)r_glowSkyBleedIntensity;
void * const imp_r_gpuSync = (void *)(uintptr_t)r_gpuSync;
void * const imp_r_highLodDist = (void *)(uintptr_t)r_highLodDist;
void * const imp_r_ignoreHwGamma = (void *)(uintptr_t)r_ignoreHwGamma;
void * const imp_r_lightMap = (void *)(uintptr_t)r_lightMap;
void * const imp_r_lightTweakAmbient = (void *)(uintptr_t)r_lightTweakAmbient;
void * const imp_r_lightTweakAmbientColor = (void *)(uintptr_t)r_lightTweakAmbientColor;
void * const imp_r_lightTweakDiffuseFraction = (void *)(uintptr_t)r_lightTweakDiffuseFraction;
void * const imp_r_lightTweakSunColor = (void *)(uintptr_t)r_lightTweakSunColor;
void * const imp_r_lightTweakSunDiffuseColor = (void *)(uintptr_t)r_lightTweakSunDiffuseColor;
void * const imp_r_lightTweakSunDirection = (void *)(uintptr_t)r_lightTweakSunDirection;
void * const imp_r_lightTweakSunLight = (void *)(uintptr_t)r_lightTweakSunLight;
void * const imp_r_lockPvs = (void *)(uintptr_t)r_lockPvs;
void * const imp_r_lodBias = (void *)(uintptr_t)r_lodBias;
void * const imp_r_lodScale = (void *)(uintptr_t)r_lodScale;
void * const imp_r_logFile = (void *)(uintptr_t)r_logFile;
void * const imp_r_lowLodDist = (void *)(uintptr_t)r_lowLodDist;
void * const imp_r_lowestLodDist = (void *)(uintptr_t)r_lowestLodDist;
void * const imp_r_mediumLodDist = (void *)(uintptr_t)r_mediumLodDist;
void * const imp_r_mode = (void *)(uintptr_t)r_mode;
void * const imp_r_multiGpu = (void *)(uintptr_t)r_multiGpu;
void * const imp_r_norefresh = (void *)(uintptr_t)r_norefresh;
void * const imp_r_normalMap = (void *)(uintptr_t)r_normalMap;
void * const imp_r_objectiveColorDx7Max = (void *)(uintptr_t)r_objectiveColorDx7Max;
void * const imp_r_objectiveColorDx7Min = (void *)(uintptr_t)r_objectiveColorDx7Min;
void * const imp_r_optimizeLightmaps = (void *)(uintptr_t)r_optimizeLightmaps;
void * const imp_r_optimizeXModels = (void *)(uintptr_t)r_optimizeXModels;
void * const imp_r_outdoorAwayBias = (void *)(uintptr_t)r_outdoorAwayBias;
void * const imp_r_outdoorDownBias = (void *)(uintptr_t)r_outdoorDownBias;
void * const imp_r_outdoorFeather = (void *)(uintptr_t)r_outdoorFeather;
void * const imp_r_overbrightBits = (void *)(uintptr_t)r_overbrightBits;
void * const imp_r_picmip = (void *)(uintptr_t)r_picmip;
void * const imp_r_picmip_bump = (void *)(uintptr_t)r_picmip_bump;
void * const imp_r_picmip_manual = (void *)(uintptr_t)r_picmip_manual;
void * const imp_r_picmip_spec = (void *)(uintptr_t)r_picmip_spec;
void * const imp_r_polygonOffsetBias = (void *)(uintptr_t)r_polygonOffsetBias;
void * const imp_r_polygonOffsetScale = (void *)(uintptr_t)r_polygonOffsetScale;
void * const imp_r_portalBevels = (void *)(uintptr_t)r_portalBevels;
void * const imp_r_portalBevelsOnly = (void *)(uintptr_t)r_portalBevelsOnly;
void * const imp_r_portalFineCull = (void *)(uintptr_t)r_portalFineCull;
void * const imp_r_portalMinClipArea = (void *)(uintptr_t)r_portalMinClipArea;
void * const imp_r_portalWalkLimit = (void *)(uintptr_t)r_portalWalkLimit;
void * const imp_r_railCoreWidth = (void *)(uintptr_t)r_railCoreWidth;
void * const imp_r_rendererInUse = (void *)(uintptr_t)r_rendererInUse;
void * const imp_r_rendererPreference = (void *)(uintptr_t)r_rendererPreference;
void * const imp_r_showFbColorDebug = (void *)(uintptr_t)r_showFbColorDebug;
void * const imp_r_showGroundLit = (void *)(uintptr_t)r_showGroundLit;
void * const imp_r_showLightGrid = (void *)(uintptr_t)r_showLightGrid;
void * const imp_r_showMissingLightGrid = (void *)(uintptr_t)r_showMissingLightGrid;
void * const imp_r_showPortals = (void *)(uintptr_t)r_showPortals;
void * const imp_r_showSModelNames = (void *)(uintptr_t)r_showSModelNames;
void * const imp_r_showSurfCounts = (void *)(uintptr_t)r_showSurfCounts;
void * const imp_r_showTriCounts = (void *)(uintptr_t)r_showTriCounts;
void * const imp_r_showTris = (void *)(uintptr_t)r_showTris;
void * const imp_r_showVertCounts = (void *)(uintptr_t)r_showVertCounts;
void * const imp_r_singleCell = (void *)(uintptr_t)r_singleCell;
void * const imp_r_skinCache = (void *)(uintptr_t)r_skinCache;
void * const imp_r_skipBackEnd = (void *)(uintptr_t)r_skipBackEnd;
void * const imp_r_skipPvs = (void *)(uintptr_t)r_skipPvs;
void * const imp_r_smc_enable = (void *)(uintptr_t)r_smc_enable;
void * const imp_r_specularColorScale = (void *)(uintptr_t)r_specularColorScale;
void * const imp_r_specularMap = (void *)(uintptr_t)r_specularMap;
void * const imp_r_sun_from_dvars = (void *)(uintptr_t)r_sun_from_dvars;
void * const imp_r_swapInterval = (void *)(uintptr_t)r_swapInterval;
void * const imp_r_testFill = (void *)(uintptr_t)r_testFill;
void * const imp_r_testFillEnable = (void *)(uintptr_t)r_testFillEnable;
void * const imp_r_testTransform = (void *)(uintptr_t)r_testTransform;
void * const imp_r_textureMode = (void *)(uintptr_t)r_textureMode;
void * const imp_r_vc_makelog = (void *)(uintptr_t)r_vc_makelog;
void * const imp_r_vc_showlog = (void *)(uintptr_t)r_vc_showlog;
void * const imp_r_xdebug = (void *)(uintptr_t)r_xdebug;
void * const imp_r_zfar = (void *)(uintptr_t)r_zfar;
void * const imp_r_znear = (void *)(uintptr_t)r_znear;
void * const imp_r_znear_depthhack = (void *)(uintptr_t)r_znear_depthhack;
void * const imp_rcon_password = (void *)(uintptr_t)rcon_password;
void * const imp_re = (void *)(uintptr_t)re;
void * const imp_rg = (void *)(uintptr_t)rg;
void * const imp_rgp = (void *)(uintptr_t)rgp;
void * const imp_ri = (void *)(uintptr_t)ri;
void * const imp_riflePriorityMap = (void *)(uintptr_t)riflePriorityMap;
void * const imp_s_sundvars = (void *)(uintptr_t)s_sundvars;
void * const imp_sc_blur = (void *)(uintptr_t)sc_blur;
void * const imp_sc_enable = (void *)(uintptr_t)sc_enable;
void * const imp_sc_showDebug = (void *)(uintptr_t)sc_showDebug;
void * const imp_scene = (void *)(uintptr_t)scene;
void * const imp_scrAnimPub = (void *)(uintptr_t)scrAnimPub;
void * const imp_scrCompileGlob = (void *)(uintptr_t)scrCompileGlob;
void * const imp_scrCompilePub = (void *)(uintptr_t)scrCompilePub;
void * const imp_scrMemTreePub = (void *)(uintptr_t)scrMemTreePub;
void * const imp_scrParserPub = (void *)(uintptr_t)scrParserPub;
void * const imp_scrVarPub = (void *)(uintptr_t)scrVarPub;
void * const imp_scrVmPub = (void *)(uintptr_t)scrVmPub;
void * const imp_scr_const = (void *)(uintptr_t)scr_const;
void * const imp_sharedUiInfo = (void *)(uintptr_t)sharedUiInfo;
void * const imp_singleClientEvents = (void *)(uintptr_t)singleClientEvents;
void * const imp_snd_bits = (void *)(uintptr_t)snd_bits;
void * const imp_snd_enableReverb = (void *)(uintptr_t)snd_enableReverb;
void * const imp_snd_errorOnMissing = (void *)(uintptr_t)snd_errorOnMissing;
void * const imp_snd_khz = (void *)(uintptr_t)snd_khz;
void * const imp_snd_roomStrings = (void *)(uintptr_t)snd_roomStrings;
void * const imp_snd_stereo = (void *)(uintptr_t)snd_stereo;
void * const imp_snd_touchStreamFilesOnLoad = (void *)(uintptr_t)snd_touchStreamFilesOnLoad;
void * const imp_sortedDvars = (void *)(uintptr_t)sortedDvars;
void * const imp_speex_nb_mode = (void *)(uintptr_t)speex_nb_mode;
void * const imp_speex_uwb_mode = (void *)(uintptr_t)speex_uwb_mode;
void * const imp_speex_wb_mode = (void *)(uintptr_t)speex_wb_mode;
void * const imp_stopspeed = (void *)(uintptr_t)stopspeed;
void * const imp_sunFlareArray = (void *)(uintptr_t)sunFlareArray;
void * const imp_sv = (void *)(uintptr_t)sv;
void * const imp_sv_allowAnonymous = (void *)(uintptr_t)sv_allowAnonymous;
void * const imp_sv_allowDownload = (void *)(uintptr_t)sv_allowDownload;
void * const imp_sv_allowedClan1 = (void *)(uintptr_t)sv_allowedClan1;
void * const imp_sv_allowedClan2 = (void *)(uintptr_t)sv_allowedClan2;
void * const imp_sv_cheats = (void *)(uintptr_t)sv_cheats;
void * const imp_sv_debugRate = (void *)(uintptr_t)sv_debugRate;
void * const imp_sv_debugReliableCmds = (void *)(uintptr_t)sv_debugReliableCmds;
void * const imp_sv_disableClientConsole = (void *)(uintptr_t)sv_disableClientConsole;
void * const imp_sv_floodProtect = (void *)(uintptr_t)sv_floodProtect;
void * const imp_sv_fps = (void *)(uintptr_t)sv_fps;
void * const imp_sv_gametype = (void *)(uintptr_t)sv_gametype;
void * const imp_sv_hostname = (void *)(uintptr_t)sv_hostname;
void * const imp_sv_iwdNames = (void *)(uintptr_t)sv_iwdNames;
void * const imp_sv_iwds = (void *)(uintptr_t)sv_iwds;
void * const imp_sv_kickBanTime = (void *)(uintptr_t)sv_kickBanTime;
void * const imp_sv_mapRotation = (void *)(uintptr_t)sv_mapRotation;
void * const imp_sv_mapRotationCurrent = (void *)(uintptr_t)sv_mapRotationCurrent;
void * const imp_sv_mapname = (void *)(uintptr_t)sv_mapname;
void * const imp_sv_maxPing = (void *)(uintptr_t)sv_maxPing;
void * const imp_sv_maxRate = (void *)(uintptr_t)sv_maxRate;
void * const imp_sv_maxclients = (void *)(uintptr_t)sv_maxclients;
void * const imp_sv_minPing = (void *)(uintptr_t)sv_minPing;
void * const imp_showpackets = (void *)(uintptr_t)showpackets;
void * const imp_sv_packet_info = (void *)(uintptr_t)sv_packet_info;
void * const imp_sv_padPackets = (void *)(uintptr_t)sv_padPackets;
void * const imp_sv_paused = (void *)(uintptr_t)sv_paused;
void * const imp_sv_privateClients = (void *)(uintptr_t)sv_privateClients;
void * const imp_sv_privatePassword = (void *)(uintptr_t)sv_privatePassword;
void * const imp_sv_pure = (void *)(uintptr_t)sv_pure;
void * const imp_sv_reconnectlimit = (void *)(uintptr_t)sv_reconnectlimit;
void * const imp_sv_referencedIwdNames = (void *)(uintptr_t)sv_referencedIwdNames;
void * const imp_sv_referencedIwds = (void *)(uintptr_t)sv_referencedIwds;
void * const imp_sv_serverId_value = (void *)(uintptr_t)sv_serverId_value;
void * const imp_sv_serverid = (void *)(uintptr_t)sv_serverid;
void * const imp_sv_showAverageBPS = (void *)(uintptr_t)sv_showAverageBPS;
void * const imp_sv_showCommands = (void *)(uintptr_t)sv_showCommands;
void * const imp_sv_timeout = (void *)(uintptr_t)sv_timeout;
void * const imp_sv_voice = (void *)(uintptr_t)sv_voice;
void * const imp_sv_voiceQuality = (void *)(uintptr_t)sv_voiceQuality;
void * const imp_sv_zombietime = (void *)(uintptr_t)sv_zombietime;
void * const imp_svs = (void *)(uintptr_t)svs;
void * const imp_tess = (void *)(uintptr_t)tess;
void * const imp_theFxHelper = (void *)(uintptr_t)theFxHelper;
void * const imp_theFxScheduler = (void *)(uintptr_t)theFxScheduler;
void * const imp_updateScreenCalled = (void *)(uintptr_t)updateScreenCalled;
void * const imp_var_typename = (void *)(uintptr_t)var_typename;
void * const imp_vbr_nb_thresh = (void *)(uintptr_t)vbr_nb_thresh;
void * const imp_vec3_colorintensity = (void *)(uintptr_t)vec3_colorintensity;
void * const imp_vec3_origin = (void *)(uintptr_t)vec3_origin;
void * const imp_vidConfig = (void *)(uintptr_t)vidConfig;
void * const imp_vid_xpos = (void *)(uintptr_t)vid_xpos;
void * const imp_vid_ypos = (void *)(uintptr_t)vid_ypos;
void * const imp_voice_current_scaler = (void *)(uintptr_t)voice_current_scaler;
void * const imp_voice_current_voicelevel = (void *)(uintptr_t)voice_current_voicelevel;
void * const imp_voice_deadChat = (void *)(uintptr_t)voice_deadChat;
void * const imp_voice_global = (void *)(uintptr_t)voice_global;
void * const imp_voice_localEcho = (void *)(uintptr_t)voice_localEcho;
void * const imp_zcalloc = (void *)(uintptr_t)zcalloc;
void * const imp_zcfree = (void *)(uintptr_t)zcfree;
