.data

/* Local label stubs (from jump tables in naked ASM) */
.globl .Lf17fea4_0017ffad
.Lf17fea4_0017ffad:
    .space 64, 0

.globl .Lf1d91a4_001d92d4
.Lf1d91a4_001d92d4:
    .space 64, 0

/* C++ static local variables */
.globl __ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.180
__ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.180:
    .space 64, 0

.globl __ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.181
__ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.181:
    .space 64, 0

.globl __ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.182
__ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.182:
    .space 64, 0

.globl __ZZ29Material_TechniqueTypeForNamePKcE5C.359
__ZZ29Material_TechniqueTypeForNamePKcE5C.359:
    .long str_00227b74  /* [0]  "depth prepass" */
    .long str_00227b84  /* [1]  "sky" */
    .long str_00227b8c  /* [2]  "build floatz" */
    .long str_00227b9c  /* [3]  "unlit no fog" */
    .long str_00227bac  /* [4]  "unlit linear fog" */
    .long str_00227bc0  /* [5]  "unlit exp fog" */
    .long str_00227bd0  /* [6]  "lightmap no fog" */
    .long str_00227be4  /* [7]  "lightmap linear fog" */
    .long str_00227bfc  /* [8]  "lightmap exp fog" */
    .long str_00227c10  /* [9]  "lightprobe no fog" */
    .long str_00227c24  /* [10] "lightprobe linear fog" */
    .long str_00227c3c  /* [11] "lightprobe exp fog" */
    .long str_00227c54  /* [12] "lightprobe smodel no fog" */
    .long str_00227c70  /* [13] "lightprobe smodel linear fog" */
    .long str_00227c90  /* [14] "lightprobe smodel exp fog" */
    .long str_00227cac  /* [15] "lightprobe smodel cached no fog" */
    .long str_00227cd0  /* [16] "lightprobe smodel cached linear fog" */
    .long str_00227cf8  /* [17] "lightprobe smodel cached exp fog" */
    .long str_00227d1c  /* [18] "pointlight no fog" */
    .long str_00227d30  /* [19] "pointlight linear fog" */
    .long str_00227d48  /* [20] "pointlight exp fog" */
    .long str_00227d60  /* [21] "emissive no fog" */
    .long str_00227d74  /* [22] "emissive linear fog" */
    .long str_00227d8c  /* [23] "emissive exp fog" */
    .long str_00227da0  /* [24] "emissive feathered no fog" */
    .long str_00227dbc  /* [25] "emissive feathered linear fog" */
    .long str_00227ddc  /* [26] "emissive feathered exp fog" */
    .long str_00227dfc  /* [27] "fakelight normal" */
    .long str_00227e10  /* [28] "fakelight view" */
    .long str_00227e24  /* [29] "solid wireframe" */
    .long str_00227e38  /* [30] "shaded wireframe" */
    .long str_00227e4c  /* [31] "shadowcookie caster" */
    .long str_00227e64  /* [32] "shadowcookie receiver" */
    .long str_00227e7c  /* [33] "debug bumpmap" */

/* 'string' used as a global variable name */
.globl string
string:
    .space 1024, 0

