.data

/* Local label stubs (from jump tables in naked ASM) */
.globl .Lf17fea4_0017ffad
.Lf17fea4_0017ffad:
    .space 64, 0

.globl .Lf1d91a4_001d92d4
.Lf1d91a4_001d92d4:
    .space 64, 0

/* C++ static local variables */
.globl __ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.180
__ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.180:
    .space 64, 0

.globl __ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.181
__ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.181:
    .space 64, 0

.globl __ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.182
__ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.182:
    .space 64, 0

.globl __ZZ29Material_TechniqueTypeForNamePKcE5C.359
__ZZ29Material_TechniqueTypeForNamePKcE5C.359:
    .space 64, 0

/* 'string' used as a global variable name */
.globl string
string:
    .space 1024, 0

