.data

.globl CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.180
CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.180:
    .space 256

.globl CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.181
CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.181:
    .space 256

.globl CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.182
CG_DrawPlayerStance_rectDef_s_const___float___Font_s___float__int___C.182:
    .space 256

.globl _ZN11FxBoltFrame12g_mFrameListE
_ZN11FxBoltFrame12g_mFrameListE:
    .space 256

.globl _ZTV5Cloud
_ZTV5Cloud:
    .space 256

.globl _ZTV8Cylinder
_ZTV8Cylinder:
    .space 256

.globl _ZTV6Effect
_ZTV6Effect:
    .space 256

.globl _ZTV7Emitter
_ZTV7Emitter:
    .space 256

.globl _ZTV5Light
_ZTV5Light:
    .space 256

.globl _ZTV4Line
_ZTV4Line:
    .space 256

.globl _ZTV16OrientedParticle
_ZTV16OrientedParticle:
    .space 256

.globl _ZTV8Particle
_ZTV8Particle:
    .space 256

.globl _ZTV4Tail
_ZTV4Tail:
    .space 256

.globl __ZTI14COpenGLTexture
__ZTI14COpenGLTexture:
    .space 256

.globl __ZTI17IDirect3DTexture9
__ZTI17IDirect3DTexture9:
    .space 256

.globl __ZTV10COpenGLVAO
__ZTV10COpenGLVAO:
    .space 256

.globl __ZTV11CColorArray
__ZTV11CColorArray:
    .space 256

.globl __ZTV12CNormalArray
__ZTV12CNormalArray:
    .space 256

.globl __ZTV12CVertexArray
__ZTV12CVertexArray:
    .space 256

.globl __ZTV14COpenGLTexture
__ZTV14COpenGLTexture:
    .space 256

.globl __ZTV14CTexCoordArray
__ZTV14CTexCoordArray:
    .space 256

.globl __ZTV15CCacheInfoBlock
__ZTV15CCacheInfoBlock:
    .space 256

.globl __ZTV15CColorConverter
__ZTV15CColorConverter:
    .space 256

.globl __ZTV17IDirect3DTexture9
__ZTV17IDirect3DTexture9:
    .space 256

.globl __ZTV18IDirect3DResource9
__ZTV18IDirect3DResource9:
    .space 256

.globl __ZTV20CSecondaryColorArray
__ZTV20CSecondaryColorArray:
    .space 256

.globl __ZTV21IDirect3DBaseTexture9
__ZTV21IDirect3DBaseTexture9:
    .space 256

.globl __ZTV21IDirect3DCubeTexture9
__ZTV21IDirect3DCubeTexture9:
    .space 256

.globl __ZTV22CVAOPacketProgrammable
__ZTV22CVAOPacketProgrammable:
    .space 256

.globl __ZTV22IDirect3DVertexShader9
__ZTV22IDirect3DVertexShader9:
    .space 256

.globl __ZTV23CVAOPacketFixedFunction
__ZTV23CVAOPacketFixedFunction:
    .space 256

.globl __ZTV23IDirect3DVolumeTexture9
__ZTV23IDirect3DVolumeTexture9:
    .space 256

.globl __ZTV5Flash
__ZTV5Flash:
    .space 256

.globl __ZTV7CBaseVA
__ZTV7CBaseVA:
    .space 256

.globl __ZTV8IUnknown
__ZTV8IUnknown:
    .space 256

.globl _ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.180
_ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.180:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.181
_ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.181:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.182
_ZZ19CG_DrawPlayerStancePK10rectDef_sPfP6Font_sfiE5C.182:
    .space 64

.text
.globl .Lf17fea4_0017ffad
.Lf17fea4_0017ffad:
    ret

.globl .Lf1d91a4_001d92d4
.Lf1d91a4_001d92d4:
    ret
