.data
.globl _ZZN16CStringEdPackage9ParseLineEPKchE5C.208
_ZZN16CStringEdPackage9ParseLineEPKchE5C.208:
    .space 2048

.globl _ZN12UI_Component1gE
_ZN12UI_Component1gE:
    .space 256

.globl _ZZN17PrimitiveTemplate15ParseGroupFlagsEPKcPiE5C.148
_ZZN17PrimitiveTemplate15ParseGroupFlagsEPKcPiE5C.148:
    .space 256

.globl _Z13FS_CreatePathPc.eh
_Z13FS_CreatePathPc.eh:
    .space 16

.globl _ZZ29Material_TechniqueTypeForNamePKcE5C.359
_ZZ29Material_TechniqueTypeForNamePKcE5C.359:
    .space 256

.globl _ZTV12IncludeClass
_ZTV12IncludeClass:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.180
_ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.180:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.181
_ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.181:
    .space 64

.globl _ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.182
_ZZ19CG_DrawPlayerStancePK9rectDef_sPfP6Font_sfiE5C.182:
    .space 64
